// Code generated by aru model:build from model.go. DO NOT EDIT.

package wallet

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Charges starts a query on the table of Charge, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Charges(db model.DB) *ChargeQuery { return &ChargeQuery{b: chargeTable.Query(db)} }

// ChargeQuery is a query on the table of Charge.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Charge rows or a value; there is
// no way to run one without a Grant.
type ChargeQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *ChargeQuery) Base() *model.Builder { return q.b }

// New returns an empty Charge on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *ChargeQuery) New() (*Charge, error) {
	e, err := q.b.NewModelInstance(nil)
	return chargeOf(e), err
}

// ChargeCollection is rows of Charge, as a query returns them.
type ChargeCollection []*Charge

// ChargeCollectionOf converts rows of the table of Charge. A nil input is a nil
// collection.
func ChargeCollectionOf(rows model.Rows) ChargeCollection {
	if rows == nil {
		return nil
	}
	out := make(ChargeCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Charge)
	}
	return out
}

func chargeOf(e model.Entity) *Charge {
	row, _ := e.(*Charge)
	return row
}

// chargeColumn turns a closure over ChargeQuery into one over the core builder, so
// passing func(*ChargeQuery) where a column goes adds a parenthesised group.
func chargeColumn(column any) any {
	if group, ok := column.(func(*ChargeQuery)); ok {
		return func(b *model.Builder) { group(&ChargeQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *ChargeQuery) Clone() *ChargeQuery { return &ChargeQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*ChargeQuery) in place of the column adds a group.
func (q *ChargeQuery) Where(column any, args ...any) *ChargeQuery {
	q.b.Where(chargeColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*ChargeQuery) in place of the column adds a group.
func (q *ChargeQuery) OrWhere(column any, args ...any) *ChargeQuery {
	q.b.OrWhere(chargeColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *ChargeQuery) WhereNot(column any, args ...any) *ChargeQuery {
	q.b.WhereNot(chargeColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *ChargeQuery) OrWhereNot(column any, args ...any) *ChargeQuery {
	q.b.OrWhereNot(chargeColumn(column), args...)
	return q
}

func (q *ChargeQuery) WhereIn(column any, values []any) *ChargeQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *ChargeQuery) WhereNotIn(column any, values []any) *ChargeQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *ChargeQuery) WhereNull(columns ...any) *ChargeQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *ChargeQuery) WhereNotNull(columns ...any) *ChargeQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *ChargeQuery) WhereBetween(column any, from, to any) *ChargeQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *ChargeQuery) WhereColumn(first any, args ...any) *ChargeQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *ChargeQuery) WhereKey(id any) *ChargeQuery {
	q.b.WhereKey(id)
	return q
}

func (q *ChargeQuery) WhereExists(callback func(*query.Builder)) *ChargeQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *ChargeQuery) WhereNotExists(callback func(*query.Builder)) *ChargeQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *ChargeQuery) WhereHas(relation string, callback func(*query.Builder)) *ChargeQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *ChargeQuery) OrWhereHas(relation string, callback func(*query.Builder)) *ChargeQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *ChargeQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *ChargeQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *ChargeQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *ChargeQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *ChargeQuery) WhereRelation(relation string, column any, args ...any) *ChargeQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *ChargeQuery) OrWhereRelation(relation string, column any, args ...any) *ChargeQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *ChargeQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *ChargeQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *ChargeQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *ChargeQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *ChargeQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *ChargeQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *ChargeQuery) OrHas(relation, operator string, count int) *ChargeQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *ChargeQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *ChargeQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *ChargeQuery) OrDoesntHave(relation string) *ChargeQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *ChargeQuery) Select(columns ...any) *ChargeQuery {
	q.b.Select(columns...)
	return q
}

func (q *ChargeQuery) AddSelect(columns ...any) *ChargeQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *ChargeQuery) SelectRaw(expression string, bindings ...any) *ChargeQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *ChargeQuery) Join(table any, first any, args ...any) *ChargeQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *ChargeQuery) GroupBy(groups ...any) *ChargeQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *ChargeQuery) OrderBy(column any, direction ...string) *ChargeQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *ChargeQuery) OrderByDesc(column any) *ChargeQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *ChargeQuery) Latest(column ...string) *ChargeQuery {
	q.b.Latest(column...)
	return q
}

func (q *ChargeQuery) Oldest(column ...string) *ChargeQuery {
	q.b.Oldest(column...)
	return q
}

func (q *ChargeQuery) Limit(value int) *ChargeQuery {
	q.b.Limit(value)
	return q
}

func (q *ChargeQuery) Offset(value int) *ChargeQuery {
	q.b.Offset(value)
	return q
}

func (q *ChargeQuery) ForPage(page, perPage int) *ChargeQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *ChargeQuery) With(relations ...string) *ChargeQuery {
	q.b.With(relations...)
	return q
}

func (q *ChargeQuery) WithCount(relations ...string) *ChargeQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *ChargeQuery) WithExists(relation string) *ChargeQuery {
	q.b.WithExists(relation)
	return q
}

func (q *ChargeQuery) WithSum(relation, column string) *ChargeQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *ChargeQuery) WithAvg(relation, column string) *ChargeQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *ChargeQuery) WithMin(relation, column string) *ChargeQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *ChargeQuery) WithMax(relation, column string) *ChargeQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *ChargeQuery) Without(relations ...string) *ChargeQuery {
	q.b.Without(relations...)
	return q
}

func (q *ChargeQuery) WithoutGlobalScope(identifier string) *ChargeQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *ChargeQuery) WithoutGlobalScopes(identifiers ...string) *ChargeQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *ChargeQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (ChargeCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return ChargeCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *ChargeQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Charge, error) {
	e, err := q.b.First(ctx, g, columns...)
	return chargeOf(e), err
}

func (q *ChargeQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Charge, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return chargeOf(e), err
}

func (q *ChargeQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Charge, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return chargeOf(e), err
}

func (q *ChargeQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Charge, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return chargeOf(e), err
}

func (q *ChargeQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Charge, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return chargeOf(e), err
}

func (q *ChargeQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Charge, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return chargeOf(e), err
}

func (q *ChargeQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Charge, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return chargeOf(e), err
}

func (q *ChargeQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Charge, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return chargeOf(e), err
}

func (q *ChargeQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (ChargeCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return ChargeCollectionOf(rows), err
}

func (q *ChargeQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Charge, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return chargeOf(e), err
}

func (q *ChargeQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Charge, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return chargeOf(e), err
}

func (q *ChargeQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Charge, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return chargeOf(e), err
}

func (q *ChargeQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Charge, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return chargeOf(e), err
}

func (q *ChargeQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (ChargeCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return ChargeCollectionOf(rows), meta, err
}

func (q *ChargeQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (ChargeCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return ChargeCollectionOf(rows), meta, err
}

func (q *ChargeQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (ChargeCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return ChargeCollectionOf(rows), meta, err
}

func (q *ChargeQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(ChargeCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(ChargeCollectionOf(rows), page)
	})
}

func (q *ChargeQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Charge, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(chargeOf(e), index)
	})
}

func (q *ChargeQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Charge, error] {
	return func(yield func(*Charge, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(chargeOf(e), err) {
				return
			}
		}
	}
}

func (q *ChargeQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *ChargeQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *ChargeQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *ChargeQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *ChargeQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *ChargeQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *ChargeQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *ChargeQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *ChargeQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *ChargeQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *ChargeQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *ChargeQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *ChargeQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *ChargeQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *ChargeQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *ChargeQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *ChargeQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *ChargeQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *ChargeQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c ChargeCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c ChargeCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c ChargeCollection) Find(key any) *Charge { return chargeOf(c.Rows().Find(key)) }

func (c ChargeCollection) FindOrFail(key any) (*Charge, error) {
	e, err := c.Rows().FindOrFail(key)
	return chargeOf(e), err
}

func (c ChargeCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c ChargeCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c ChargeCollection) Only(keys ...any) ChargeCollection {
	return ChargeCollectionOf(c.Rows().Only(keys...))
}

func (c ChargeCollection) Except(keys ...any) ChargeCollection {
	return ChargeCollectionOf(c.Rows().Except(keys...))
}

func (c ChargeCollection) Unique() ChargeCollection { return ChargeCollectionOf(c.Rows().Unique()) }

func (c ChargeCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c ChargeCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c ChargeCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c ChargeCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (ChargeCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return ChargeCollectionOf(rows), err
}

func (c ChargeCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Charge; it shadows the untyped one the
// embedded model promotes.
func (row *Charge) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Charge, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return chargeOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Charge) Replicate(except ...string) (*Charge, error) {
	e, err := row.Model.Replicate(except...)
	return chargeOf(e), err
}
