// Code generated by aru model:build from model.go. DO NOT EDIT.

package wallet

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Conversions starts a query on the table of Conversion, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Conversions(db model.DB) *ConversionQuery { return &ConversionQuery{b: conversionTable.Query(db)} }

// ConversionQuery is a query on the table of Conversion.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Conversion rows or a value; there is
// no way to run one without a Grant.
type ConversionQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *ConversionQuery) Base() *model.Builder { return q.b }

// New returns an empty Conversion on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *ConversionQuery) New() (*Conversion, error) {
	e, err := q.b.NewModelInstance(nil)
	return conversionOf(e), err
}

// ConversionCollection is rows of Conversion, as a query returns them.
type ConversionCollection []*Conversion

// ConversionCollectionOf converts rows of the table of Conversion. A nil input is a nil
// collection.
func ConversionCollectionOf(rows model.Rows) ConversionCollection {
	if rows == nil {
		return nil
	}
	out := make(ConversionCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Conversion)
	}
	return out
}

func conversionOf(e model.Entity) *Conversion {
	row, _ := e.(*Conversion)
	return row
}

// conversionColumn turns a closure over ConversionQuery into one over the core builder, so
// passing func(*ConversionQuery) where a column goes adds a parenthesised group.
func conversionColumn(column any) any {
	if group, ok := column.(func(*ConversionQuery)); ok {
		return func(b *model.Builder) { group(&ConversionQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *ConversionQuery) Clone() *ConversionQuery { return &ConversionQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*ConversionQuery) in place of the column adds a group.
func (q *ConversionQuery) Where(column any, args ...any) *ConversionQuery {
	q.b.Where(conversionColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*ConversionQuery) in place of the column adds a group.
func (q *ConversionQuery) OrWhere(column any, args ...any) *ConversionQuery {
	q.b.OrWhere(conversionColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *ConversionQuery) WhereNot(column any, args ...any) *ConversionQuery {
	q.b.WhereNot(conversionColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *ConversionQuery) OrWhereNot(column any, args ...any) *ConversionQuery {
	q.b.OrWhereNot(conversionColumn(column), args...)
	return q
}

func (q *ConversionQuery) WhereIn(column any, values []any) *ConversionQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *ConversionQuery) WhereNotIn(column any, values []any) *ConversionQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *ConversionQuery) WhereNull(columns ...any) *ConversionQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *ConversionQuery) WhereNotNull(columns ...any) *ConversionQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *ConversionQuery) WhereBetween(column any, from, to any) *ConversionQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *ConversionQuery) WhereColumn(first any, args ...any) *ConversionQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *ConversionQuery) WhereKey(id any) *ConversionQuery {
	q.b.WhereKey(id)
	return q
}

func (q *ConversionQuery) WhereExists(callback func(*query.Builder)) *ConversionQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *ConversionQuery) WhereNotExists(callback func(*query.Builder)) *ConversionQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *ConversionQuery) WhereHas(relation string, callback func(*query.Builder)) *ConversionQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *ConversionQuery) OrWhereHas(relation string, callback func(*query.Builder)) *ConversionQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *ConversionQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *ConversionQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *ConversionQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *ConversionQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *ConversionQuery) WhereRelation(relation string, column any, args ...any) *ConversionQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *ConversionQuery) OrWhereRelation(relation string, column any, args ...any) *ConversionQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *ConversionQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *ConversionQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *ConversionQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *ConversionQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *ConversionQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *ConversionQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *ConversionQuery) OrHas(relation, operator string, count int) *ConversionQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *ConversionQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *ConversionQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *ConversionQuery) OrDoesntHave(relation string) *ConversionQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *ConversionQuery) Select(columns ...any) *ConversionQuery {
	q.b.Select(columns...)
	return q
}

func (q *ConversionQuery) AddSelect(columns ...any) *ConversionQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *ConversionQuery) SelectRaw(expression string, bindings ...any) *ConversionQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *ConversionQuery) Join(table any, first any, args ...any) *ConversionQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *ConversionQuery) GroupBy(groups ...any) *ConversionQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *ConversionQuery) OrderBy(column any, direction ...string) *ConversionQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *ConversionQuery) OrderByDesc(column any) *ConversionQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *ConversionQuery) Latest(column ...string) *ConversionQuery {
	q.b.Latest(column...)
	return q
}

func (q *ConversionQuery) Oldest(column ...string) *ConversionQuery {
	q.b.Oldest(column...)
	return q
}

func (q *ConversionQuery) Limit(value int) *ConversionQuery {
	q.b.Limit(value)
	return q
}

func (q *ConversionQuery) Offset(value int) *ConversionQuery {
	q.b.Offset(value)
	return q
}

func (q *ConversionQuery) ForPage(page, perPage int) *ConversionQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *ConversionQuery) With(relations ...string) *ConversionQuery {
	q.b.With(relations...)
	return q
}

func (q *ConversionQuery) WithCount(relations ...string) *ConversionQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *ConversionQuery) WithExists(relation string) *ConversionQuery {
	q.b.WithExists(relation)
	return q
}

func (q *ConversionQuery) WithSum(relation, column string) *ConversionQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *ConversionQuery) WithAvg(relation, column string) *ConversionQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *ConversionQuery) WithMin(relation, column string) *ConversionQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *ConversionQuery) WithMax(relation, column string) *ConversionQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *ConversionQuery) Without(relations ...string) *ConversionQuery {
	q.b.Without(relations...)
	return q
}

func (q *ConversionQuery) WithoutGlobalScope(identifier string) *ConversionQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *ConversionQuery) WithoutGlobalScopes(identifiers ...string) *ConversionQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *ConversionQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (ConversionCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return ConversionCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *ConversionQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Conversion, error) {
	e, err := q.b.First(ctx, g, columns...)
	return conversionOf(e), err
}

func (q *ConversionQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Conversion, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return conversionOf(e), err
}

func (q *ConversionQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Conversion, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return conversionOf(e), err
}

func (q *ConversionQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Conversion, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return conversionOf(e), err
}

func (q *ConversionQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Conversion, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return conversionOf(e), err
}

func (q *ConversionQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Conversion, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return conversionOf(e), err
}

func (q *ConversionQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Conversion, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return conversionOf(e), err
}

func (q *ConversionQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Conversion, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return conversionOf(e), err
}

func (q *ConversionQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (ConversionCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return ConversionCollectionOf(rows), err
}

func (q *ConversionQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Conversion, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return conversionOf(e), err
}

func (q *ConversionQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Conversion, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return conversionOf(e), err
}

func (q *ConversionQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Conversion, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return conversionOf(e), err
}

func (q *ConversionQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Conversion, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return conversionOf(e), err
}

func (q *ConversionQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (ConversionCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return ConversionCollectionOf(rows), meta, err
}

func (q *ConversionQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (ConversionCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return ConversionCollectionOf(rows), meta, err
}

func (q *ConversionQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (ConversionCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return ConversionCollectionOf(rows), meta, err
}

func (q *ConversionQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(ConversionCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(ConversionCollectionOf(rows), page)
	})
}

func (q *ConversionQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Conversion, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(conversionOf(e), index)
	})
}

func (q *ConversionQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Conversion, error] {
	return func(yield func(*Conversion, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(conversionOf(e), err) {
				return
			}
		}
	}
}

func (q *ConversionQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *ConversionQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *ConversionQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *ConversionQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *ConversionQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *ConversionQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *ConversionQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *ConversionQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *ConversionQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *ConversionQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *ConversionQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *ConversionQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *ConversionQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *ConversionQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *ConversionQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *ConversionQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *ConversionQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *ConversionQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *ConversionQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c ConversionCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c ConversionCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c ConversionCollection) Find(key any) *Conversion { return conversionOf(c.Rows().Find(key)) }

func (c ConversionCollection) FindOrFail(key any) (*Conversion, error) {
	e, err := c.Rows().FindOrFail(key)
	return conversionOf(e), err
}

func (c ConversionCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c ConversionCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c ConversionCollection) Only(keys ...any) ConversionCollection {
	return ConversionCollectionOf(c.Rows().Only(keys...))
}

func (c ConversionCollection) Except(keys ...any) ConversionCollection {
	return ConversionCollectionOf(c.Rows().Except(keys...))
}

func (c ConversionCollection) Unique() ConversionCollection {
	return ConversionCollectionOf(c.Rows().Unique())
}

func (c ConversionCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c ConversionCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c ConversionCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c ConversionCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (ConversionCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return ConversionCollectionOf(rows), err
}

func (c ConversionCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Conversion; it shadows the untyped one the
// embedded model promotes.
func (row *Conversion) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Conversion, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return conversionOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Conversion) Replicate(except ...string) (*Conversion, error) {
	e, err := row.Model.Replicate(except...)
	return conversionOf(e), err
}
