// Code generated by aru model:build from model.go. DO NOT EDIT.

package wallet

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Entries starts a query on the table of Entry, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Entries(db model.DB) *EntryQuery { return &EntryQuery{b: entryTable.Query(db)} }

// EntryQuery is a query on the table of Entry.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Entry rows or a value; there is
// no way to run one without a Grant.
type EntryQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *EntryQuery) Base() *model.Builder { return q.b }

// New returns an empty Entry on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *EntryQuery) New() (*Entry, error) {
	e, err := q.b.NewModelInstance(nil)
	return entryOf(e), err
}

// EntryCollection is rows of Entry, as a query returns them.
type EntryCollection []*Entry

// EntryCollectionOf converts rows of the table of Entry. A nil input is a nil
// collection.
func EntryCollectionOf(rows model.Rows) EntryCollection {
	if rows == nil {
		return nil
	}
	out := make(EntryCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Entry)
	}
	return out
}

func entryOf(e model.Entity) *Entry {
	row, _ := e.(*Entry)
	return row
}

// entryColumn turns a closure over EntryQuery into one over the core builder, so
// passing func(*EntryQuery) where a column goes adds a parenthesised group.
func entryColumn(column any) any {
	if group, ok := column.(func(*EntryQuery)); ok {
		return func(b *model.Builder) { group(&EntryQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *EntryQuery) Clone() *EntryQuery { return &EntryQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*EntryQuery) in place of the column adds a group.
func (q *EntryQuery) Where(column any, args ...any) *EntryQuery {
	q.b.Where(entryColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*EntryQuery) in place of the column adds a group.
func (q *EntryQuery) OrWhere(column any, args ...any) *EntryQuery {
	q.b.OrWhere(entryColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *EntryQuery) WhereNot(column any, args ...any) *EntryQuery {
	q.b.WhereNot(entryColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *EntryQuery) OrWhereNot(column any, args ...any) *EntryQuery {
	q.b.OrWhereNot(entryColumn(column), args...)
	return q
}

func (q *EntryQuery) WhereIn(column any, values []any) *EntryQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *EntryQuery) WhereNotIn(column any, values []any) *EntryQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *EntryQuery) WhereNull(columns ...any) *EntryQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *EntryQuery) WhereNotNull(columns ...any) *EntryQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *EntryQuery) WhereBetween(column any, from, to any) *EntryQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *EntryQuery) WhereColumn(first any, args ...any) *EntryQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *EntryQuery) WhereKey(id any) *EntryQuery {
	q.b.WhereKey(id)
	return q
}

func (q *EntryQuery) WhereExists(callback func(*query.Builder)) *EntryQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *EntryQuery) WhereNotExists(callback func(*query.Builder)) *EntryQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *EntryQuery) WhereHas(relation string, callback func(*query.Builder)) *EntryQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *EntryQuery) OrWhereHas(relation string, callback func(*query.Builder)) *EntryQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *EntryQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *EntryQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *EntryQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *EntryQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *EntryQuery) WhereRelation(relation string, column any, args ...any) *EntryQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *EntryQuery) OrWhereRelation(relation string, column any, args ...any) *EntryQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *EntryQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *EntryQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *EntryQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *EntryQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *EntryQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *EntryQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *EntryQuery) OrHas(relation, operator string, count int) *EntryQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *EntryQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *EntryQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *EntryQuery) OrDoesntHave(relation string) *EntryQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *EntryQuery) Select(columns ...any) *EntryQuery {
	q.b.Select(columns...)
	return q
}

func (q *EntryQuery) AddSelect(columns ...any) *EntryQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *EntryQuery) SelectRaw(expression string, bindings ...any) *EntryQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *EntryQuery) Join(table any, first any, args ...any) *EntryQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *EntryQuery) GroupBy(groups ...any) *EntryQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *EntryQuery) OrderBy(column any, direction ...string) *EntryQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *EntryQuery) OrderByDesc(column any) *EntryQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *EntryQuery) Latest(column ...string) *EntryQuery {
	q.b.Latest(column...)
	return q
}

func (q *EntryQuery) Oldest(column ...string) *EntryQuery {
	q.b.Oldest(column...)
	return q
}

func (q *EntryQuery) Limit(value int) *EntryQuery {
	q.b.Limit(value)
	return q
}

func (q *EntryQuery) Offset(value int) *EntryQuery {
	q.b.Offset(value)
	return q
}

func (q *EntryQuery) ForPage(page, perPage int) *EntryQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *EntryQuery) With(relations ...string) *EntryQuery {
	q.b.With(relations...)
	return q
}

func (q *EntryQuery) WithCount(relations ...string) *EntryQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *EntryQuery) WithExists(relation string) *EntryQuery {
	q.b.WithExists(relation)
	return q
}

func (q *EntryQuery) WithSum(relation, column string) *EntryQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *EntryQuery) WithAvg(relation, column string) *EntryQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *EntryQuery) WithMin(relation, column string) *EntryQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *EntryQuery) WithMax(relation, column string) *EntryQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *EntryQuery) Without(relations ...string) *EntryQuery {
	q.b.Without(relations...)
	return q
}

func (q *EntryQuery) WithoutGlobalScope(identifier string) *EntryQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *EntryQuery) WithoutGlobalScopes(identifiers ...string) *EntryQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *EntryQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (EntryCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return EntryCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *EntryQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Entry, error) {
	e, err := q.b.First(ctx, g, columns...)
	return entryOf(e), err
}

func (q *EntryQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Entry, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return entryOf(e), err
}

func (q *EntryQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Entry, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return entryOf(e), err
}

func (q *EntryQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Entry, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return entryOf(e), err
}

func (q *EntryQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Entry, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return entryOf(e), err
}

func (q *EntryQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Entry, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return entryOf(e), err
}

func (q *EntryQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Entry, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return entryOf(e), err
}

func (q *EntryQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Entry, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return entryOf(e), err
}

func (q *EntryQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (EntryCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return EntryCollectionOf(rows), err
}

func (q *EntryQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Entry, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return entryOf(e), err
}

func (q *EntryQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Entry, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return entryOf(e), err
}

func (q *EntryQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Entry, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return entryOf(e), err
}

func (q *EntryQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Entry, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return entryOf(e), err
}

func (q *EntryQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (EntryCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return EntryCollectionOf(rows), meta, err
}

func (q *EntryQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (EntryCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return EntryCollectionOf(rows), meta, err
}

func (q *EntryQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (EntryCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return EntryCollectionOf(rows), meta, err
}

func (q *EntryQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(EntryCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(EntryCollectionOf(rows), page)
	})
}

func (q *EntryQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Entry, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(entryOf(e), index)
	})
}

func (q *EntryQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Entry, error] {
	return func(yield func(*Entry, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(entryOf(e), err) {
				return
			}
		}
	}
}

func (q *EntryQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *EntryQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *EntryQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *EntryQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *EntryQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *EntryQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *EntryQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *EntryQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *EntryQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *EntryQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *EntryQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *EntryQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *EntryQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *EntryQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *EntryQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *EntryQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *EntryQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *EntryQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *EntryQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c EntryCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c EntryCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c EntryCollection) Find(key any) *Entry { return entryOf(c.Rows().Find(key)) }

func (c EntryCollection) FindOrFail(key any) (*Entry, error) {
	e, err := c.Rows().FindOrFail(key)
	return entryOf(e), err
}

func (c EntryCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c EntryCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c EntryCollection) Only(keys ...any) EntryCollection {
	return EntryCollectionOf(c.Rows().Only(keys...))
}

func (c EntryCollection) Except(keys ...any) EntryCollection {
	return EntryCollectionOf(c.Rows().Except(keys...))
}

func (c EntryCollection) Unique() EntryCollection { return EntryCollectionOf(c.Rows().Unique()) }

func (c EntryCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c EntryCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c EntryCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c EntryCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (EntryCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return EntryCollectionOf(rows), err
}

func (c EntryCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Entry; it shadows the untyped one the
// embedded model promotes.
func (row *Entry) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Entry, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return entryOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Entry) Replicate(except ...string) (*Entry, error) {
	e, err := row.Model.Replicate(except...)
	return entryOf(e), err
}
