package wallet

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/arandu-io/framework/data"
	"github.com/arandu-io/hesape/database/model"
)

// The tables this package owns. They are named here rather than repeated at
// each call, because a table named in two places is a table one of them will
// rename alone.
const (
	walletsTable     = "wallets"
	operationsTable  = "wallet_operations"
	entriesTable     = "wallet_entries"
	conversionsTable = "wallet_conversions"
	chargesTable     = "wallet_charges"
)

// Wallet is a balance held for somebody, in one currency.
//
// A holder may have several: the pair of HolderID and Slug is what names one,
// so "user-1"/"main" and "user-1"/"bonus" are two balances that never mix. The
// currency and the scale are fixed when the wallet is opened, because changing
// either would reinterpret every amount already written under it.
//
// It embeds the model, so a row returned by a query carries the connection and
// can be saved again. Build new rows through Wallets: a struct literal has no
// connection and its write methods return model.ErrUnwired.
type Wallet struct {
	model.Model[Wallet]

	// ID is the identifier. It is generated by the application rather than by
	// the database, because a DEFAULT that produces a uuid is spelled
	// differently in every engine.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to. It is written from the
	// Grant and read back so the policy can compare it against the subject's
	// tenant.
	TenantID string `db:"tenant_id"`

	// HolderID is whose money this is. It is an identifier the application
	// owns -- a user, an organisation, a merchant -- and this package never
	// resolves it: what a holder is belongs to the application, and a package
	// that assumed it was a user would be wrong in every application where it
	// is not.
	HolderID string `db:"holder_id"`

	// Slug names which of the holder's wallets this is.
	Slug string `db:"slug"`

	// Name is what a person calls this wallet.
	Name string `db:"name"`

	// Description is what a person is told this wallet is for, and it is empty
	// where nobody said. It is text this package carries and never reads: what
	// a wallet is for is the application's sentence, in the application's
	// language, and a package that parsed it would be a package deciding what
	// the sentences may be.
	Description string `db:"description"`

	// Meta is what the application attaches to the wallet itself: its own facts
	// about whose money this is and why it exists.
	//
	// It is the wallet's own and not a movement's. A fact that is true of every
	// movement -- the account it settles to, the contract it belongs to -- is a
	// fact about the wallet, and attaching it to each movement instead would
	// write it into a table that only grows.
	//
	// Nothing here is read by this package, exactly as on a movement: it is not
	// indexed, not searched and not compared, and every decision about the money
	// is made from the columns beside it.
	Meta Meta `db:"meta"`

	// Currency is what the balance counts.
	Currency Currency `db:"currency"`

	// DecimalPlaces is how many minor units make one major unit of Currency.
	// It is the scale every amount on this wallet is written at, and it is
	// fixed for the life of the wallet.
	DecimalPlaces int `db:"decimal_places"`

	// Balance is the projection of the ledger, in minor units.
	//
	// The entries are the truth and this column is what they add up to. It
	// exists so that a balance is one row rather than a sum over a history
	// that only grows, and it is only ever moved by a statement that carries
	// its own guard -- never by a value read, adjusted in Go and written back.
	Balance Amount `db:"balance"`

	// CreditLimit is how far below zero this wallet may go, as a positive
	// number of minor units. Zero is the ordinary wallet, which may not go
	// below zero at all.
	//
	// It is a column and not a value the application answers for on each call,
	// because it is read by the statement that moves the money: the guard on a
	// withdrawal compares the balance against the amount less this column, in
	// the same statement, so the limit that applies is the one the row holds at
	// the moment of the write. A limit fetched a moment earlier would be a
	// limit two concurrent withdrawals could both spend.
	CreditLimit Amount `db:"credit_limit"`

	// LastSequence is the position of the newest entry on this wallet.
	//
	// It moves in the same statement as the balance, so the number an entry is
	// written with is one nothing else can be holding. It exists because a
	// statement is read in order and a timestamp cannot supply one: two entries
	// written inside the same tick of the clock are two rows an ORDER BY over
	// time cannot tell apart, and a running balance in the wrong order is a
	// statement that does not add up as somebody reads down it.
	LastSequence int64 `db:"last_sequence"`

	// Frozen stops every movement of this wallet's money.
	//
	// It is set when a reconciliation finds that the ledger no longer explains
	// the balance beside it, and cleared by the adjustment that closes the
	// difference. Nothing else writes it, and it is not a lock an application
	// takes: what it means is that this package no longer knows what this
	// wallet holds, and serving a withdrawal from a number it cannot explain is
	// how a discrepancy becomes somebody else's money.
	//
	// It is a column and not a value read before the movement, for the reason
	// the credit limit is one: the statement that moves the balance names it,
	// so the answer that applies is the one the row holds at the instant of the
	// write. A flag read a moment earlier is a flag two concurrent withdrawals
	// both saw as clear.
	Frozen Flag `db:"frozen"`

	// CreatedAt is when the wallet was opened, in UTC.
	CreatedAt time.Time `db:"created_at"`

	// UpdatedAt is when the balance last moved, in UTC.
	UpdatedAt time.Time `db:"updated_at"`
}

// Wallets returns the configured model for the wallets table.
//
// The primary key is application-generated text, so it does not increment.
// The tenant scope remains on the model's tenant_id default.
func Wallets(db *data.DB) *model.Model[Wallet] {
	m := model.NewModel[Wallet](walletsTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// Money returns an amount read at this wallet's currency and scale.
func (w Wallet) Money(amount Amount) Money {
	return Money{Amount: amount, Currency: w.Currency, DecimalPlaces: w.DecimalPlaces}
}

// OperationKind is what an operation did.
type OperationKind string

// The kinds an operation can be. An operation is one request that moved money,
// and the kind is what it was asked to do rather than what its entries look
// like: a transfer and a reversal of a deposit both write a withdrawal, and
// telling them apart afterwards is what a statement is for.
const (
	// OperationDeposit put money into one wallet.
	OperationDeposit OperationKind = "deposit"
	// OperationWithdraw took money out of one wallet.
	OperationWithdraw OperationKind = "withdraw"
	// OperationTransfer moved money between two wallets counted the same way,
	// so the number that left is the number that arrived.
	OperationTransfer OperationKind = "transfer"
	// OperationExchange moved money between two wallets that are not counted
	// the same way, so a rate decided what arrived. It is its own kind and not
	// a transfer with a note on it, because a statement that cannot tell the
	// two apart is a statement where a rate was applied and nothing says so.
	// An operation of this kind has a Conversion, and no other kind has one.
	OperationExchange OperationKind = "exchange"
	// OperationReversal undid an earlier operation.
	OperationReversal OperationKind = "reversal"
	// OperationConfirmation settled an operation that was recorded without
	// moving anything. It is its own operation and not a change to the one it
	// settles, because the ledger is appended to and never rewritten: what was
	// proposed stays on the record exactly as it was proposed, and what
	// happened is the row beside it.
	OperationConfirmation OperationKind = "confirmation"
	// OperationPurchase paid for a basket: one request, one transaction, and a
	// movement for every line of it. It is its own kind and not a run of
	// transfers, because what was bought is a fact about the request and a
	// statement that could not tell the two apart is a statement where a basket
	// reads as a person paying a shop six times in one second.
	OperationPurchase OperationKind = "purchase"
	// OperationRefund gave back some of the lines of a purchase. It is how a
	// basket is undone -- line by line, so that a basket half of which was
	// already given back cannot be given back whole.
	OperationRefund OperationKind = "refund"
	// OperationAdjustment closed a difference between a wallet's ledger and the
	// balance column beside it. It moves no balance: it appends the settled
	// entry the ledger was missing, so the sum of the entries reaches the
	// number the column already held. It is its own kind because a statement
	// that could not tell it apart from a deposit would be a statement where a
	// correction reads as money arriving.
	OperationAdjustment OperationKind = "adjustment"
)

// Operation is one request that moved money, recorded before the money moves.
//
// It is what makes a retry safe. The row carries the caller's idempotency key
// under a unique index, so a second request with the same key cannot insert a
// second operation -- the database refuses it, rather than a read deciding that
// it probably has not run yet.
type Operation struct {
	model.Model[Operation]

	// ID is the identifier, generated by the application.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to, written from the Grant.
	TenantID string `db:"tenant_id"`

	// IdempotencyKey is what the caller sent to name this request. It is
	// unique per tenant, so the same key is the same operation whatever it was
	// asked to do.
	IdempotencyKey string `db:"idempotency_key"`

	// Kind is what the operation was asked to do.
	Kind OperationKind `db:"kind"`

	// SettlesID is the operation this one settles.
	//
	// A reversal holds the id of the operation it undoes and a confirmation
	// the id of the one it makes count. Everything else holds its own id,
	// which is what lets one unique index over the kind and this column carry
	// two rules at once: an operation is reversed at most once and confirmed at
	// most once, and a row that settles nothing collides with nothing -- not
	// even with the reversal or the confirmation naming it, because those
	// differ from it in kind.
	//
	// It is stored in the column named reverses_id, which is the name the
	// column was created under. Read it with Reverses and Confirms, each of
	// which answers with the empty string where this row is not that.
	SettlesID string `db:"reverses_id"`

	// Reason is what the caller said about a reversal, and is empty on
	// everything else.
	Reason string `db:"reason"`

	// Meta is what the application attached to the request as a whole: its own
	// facts about what this money was for. Nothing in this package reads it.
	Meta Meta `db:"meta"`

	// CreatedAt is when the operation was recorded, in UTC.
	CreatedAt time.Time `db:"created_at"`
}

// Operations returns the configured model for the operations table.
func Operations(db *data.DB) *model.Model[Operation] {
	m := model.NewModel[Operation](operationsTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// Reverses is the operation this one undoes, and the empty string when it
// undoes nothing.
func (o Operation) Reverses() string {
	if o.Kind != OperationReversal || o.SettlesID == o.ID {
		return ""
	}
	return o.SettlesID
}

// Confirms is the operation this one made count, and the empty string when it
// confirms nothing.
func (o Operation) Confirms() string {
	if o.Kind != OperationConfirmation || o.SettlesID == o.ID {
		return ""
	}
	return o.SettlesID
}

// Conversion is the rate one operation applied, recorded as it was applied.
//
// It exists so that an exchange can be reproduced rather than believed. The row
// carries both sides in full -- each currency, each scale, each amount -- the
// exact fraction the rate was, the moment it was quoted, the rule the result
// was rounded under, and the part of the value no minor unit could carry. From
// those numbers alone the arithmetic can be done again years later, by somebody
// who has neither the rate provider that answered nor the code that called it.
//
// One row per operation, held by a unique index, and only an exchange has one.
// It is appended and never changed, for the reason the ledger is: a rate that
// could be corrected in place is a rate that says what somebody later wished it
// had been.
type Conversion struct {
	model.Model[Conversion]

	// ID is the identifier, generated by the application.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to, written from the Grant.
	TenantID string `db:"tenant_id"`

	// OperationID is the operation that converted. It is unique per tenant:
	// one operation applies one rate, and a second row against it would be a
	// second answer to what an exchange was worth.
	OperationID string `db:"operation_id"`

	// FromCurrency is what left, and FromDecimalPlaces is the scale it was
	// counted at. Both are copied onto the row rather than read back off the
	// wallet, because a wallet is a live record and a conversion is a fact
	// about a moment.
	FromCurrency      Currency `db:"from_currency"`
	FromDecimalPlaces int      `db:"from_decimal_places"`

	// FromAmount is how much left, in FromCurrency's minor units.
	FromAmount Amount `db:"from_amount"`

	// ToCurrency is what arrived, and ToDecimalPlaces is the scale it was
	// counted at.
	ToCurrency      Currency `db:"to_currency"`
	ToDecimalPlaces int      `db:"to_decimal_places"`

	// ToAmount is how much arrived, in ToCurrency's minor units. It is the
	// number the ledger was credited with, so the row and the entry agree by
	// construction.
	ToAmount Amount `db:"to_amount"`

	// RateNumerator and RateDenominator are the exact fraction the rate was.
	// Two integers rather than a decimal, because a rate that does not divide
	// evenly -- a third, a seventh -- has no decimal spelling that is still the
	// rate.
	RateNumerator   int64 `db:"rate_numerator"`
	RateDenominator int64 `db:"rate_denominator"`

	// QuotedAt is when the rate was obtained, in UTC. It is the provider's
	// answer and not the time of the write: a rate quoted at open and applied
	// at noon is a rate from the open.
	QuotedAt time.Time `db:"quoted_at"`

	// Rounding is the rule that produced ToAmount from the exact value.
	Rounding Rounding `db:"rounding"`

	// RemainderNumerator is what rounding left behind, over
	// RemainderDenominator, and it is smaller than one minor unit of the
	// target. It is written down because a value that is dropped without a
	// record is a value nobody can add up afterwards.
	RemainderNumerator int64 `db:"remainder_numerator"`

	// RemainderDenominator is what the remainder is a fraction of.
	RemainderDenominator int64 `db:"remainder_denominator"`

	// CreatedAt is when the conversion was written, in UTC.
	CreatedAt time.Time `db:"created_at"`
}

// Conversions returns the configured model for the conversions table.
func Conversions(db *data.DB) *model.Model[Conversion] {
	m := model.NewModel[Conversion](conversionsTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// Rate is the rate this conversion was made at, as it was quoted.
func (c Conversion) Rate() Rate {
	return Rate{
		From:        c.FromCurrency,
		To:          c.ToCurrency,
		Numerator:   c.RateNumerator,
		Denominator: c.RateDenominator,
		QuotedAt:    c.QuotedAt,
	}
}

// From is the money that left, read at the scale it was counted at.
func (c Conversion) From() Money {
	return Money{Amount: c.FromAmount, Currency: c.FromCurrency, DecimalPlaces: c.FromDecimalPlaces}
}

// To is the money that arrived, read at the scale it was counted at.
func (c Conversion) To() Money {
	return Money{Amount: c.ToAmount, Currency: c.ToCurrency, DecimalPlaces: c.ToDecimalPlaces}
}

// Exact reports that the rate divided evenly and nothing was left over.
func (c Conversion) Exact() bool { return c.RemainderNumerator == 0 }

// Charge is what one operation charged beyond the money it moved: the discount
// that lowered the payment and the fee that was taken out of it.
//
// It exists so that a receipt saying a different number from the request can say
// why, and say it in numbers rather than in a note. Every input is on the row --
// what was asked for, what was taken off, what the fee was computed from, the
// exact fraction, both bounds, who paid it and where it went -- so the whole
// calculation can be done again from the row alone, by somebody who has neither
// the provider that answered nor the code that called it.
//
// One row per operation, held by a unique index, and only an operation that
// discounted or charged has one. It is appended and never changed, for the
// reason the ledger and the recorded rates are: a fee that could be corrected in
// place is a fee that says what somebody later wished it had been.
//
// Every amount on it is in one money, named by Currency and DecimalPlaces: the
// money the payment left in. A fee is refused where that money is not also the
// money it arrives in, so there is no rate anywhere in this row.
type Charge struct {
	model.Model[Charge]

	// ID is the identifier, generated by the application.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to, written from the Grant.
	TenantID string `db:"tenant_id"`

	// OperationID is the operation that charged. It is unique per tenant: one
	// operation charges once, and a second row against it would be a second
	// answer to what a payment cost.
	OperationID string `db:"operation_id"`

	// Currency is the money every amount below is counted in, and
	// DecimalPlaces its scale. Both are copied onto the row rather than read
	// back off a wallet, because a wallet is a live record and a charge is a
	// fact about a moment.
	Currency      Currency `db:"currency"`
	DecimalPlaces int      `db:"decimal_places"`

	// RequestedAmount is what the caller asked to move, before anything was
	// taken off.
	RequestedAmount Amount `db:"requested_amount"`

	// Discount is what the payer was charged less. Zero where nothing was.
	Discount Amount `db:"discount"`

	// BaseAmount is what the fee was computed from: the requested amount less
	// the discount. It is written rather than left to be derived, because it is
	// the number the fraction below was applied to and a row that has to be
	// recomputed before it can be checked is a row that is checked less often.
	BaseAmount Amount `db:"base_amount"`

	// FeeNumerator and FeeDenominator are the exact fraction the fee was, and
	// FeeMinimum and FeeMaximum the bounds it was held between. All four are
	// recorded even where a bound decided the fee, because which of them
	// decided is the first question anybody asks about a fee that is not the
	// share of the payment.
	FeeNumerator   int64  `db:"fee_numerator"`
	FeeDenominator int64  `db:"fee_denominator"`
	FeeMinimum     Amount `db:"fee_minimum"`
	FeeMaximum     Amount `db:"fee_maximum"`

	// FeeDeductible says who paid it: false is the payer, on top of the
	// payment, and true is the receiver, out of what arrived.
	FeeDeductible Flag `db:"fee_deductible"`

	// FeeAmount is what was actually charged, and FeeWalletID the wallet it was
	// credited to. The ledger has the same numbers as entries under this
	// operation, so the row and the movement agree by construction.
	FeeAmount   Amount `db:"fee_amount"`
	FeeWalletID string `db:"fee_wallet_id"`

	// Rounding is the rule that produced FeeAmount from the exact share.
	Rounding Rounding `db:"rounding"`

	// RemainderNumerator is what truncating the share left behind, over
	// RemainderDenominator. It is zero where a bound decided the fee, because
	// then nothing was truncated.
	RemainderNumerator   int64 `db:"remainder_numerator"`
	RemainderDenominator int64 `db:"remainder_denominator"`

	// CreatedAt is when the charge was written, in UTC.
	CreatedAt time.Time `db:"created_at"`
}

// Charges returns the configured model for the charges table.
func Charges(db *data.DB) *model.Model[Charge] {
	m := model.NewModel[Charge](chargesTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// Schedule is the fee this charge was made under, as it was quoted.
func (c Charge) Schedule() FeeSchedule {
	return FeeSchedule{
		Numerator:   c.FeeNumerator,
		Denominator: c.FeeDenominator,
		Minimum:     c.FeeMinimum,
		Maximum:     c.FeeMaximum,
		Deductible:  bool(c.FeeDeductible),
		WalletID:    c.FeeWalletID,
	}
}

// Requested is what the caller asked to move, read at the scale it was counted
// at.
func (c Charge) Requested() Money {
	return Money{Amount: c.RequestedAmount, Currency: c.Currency, DecimalPlaces: c.DecimalPlaces}
}

// Base is what the fee was computed from, read at the scale it was counted at.
func (c Charge) Base() Money {
	return Money{Amount: c.BaseAmount, Currency: c.Currency, DecimalPlaces: c.DecimalPlaces}
}

// Fee is what was charged, read at the scale it was counted at.
func (c Charge) Fee() Money {
	return Money{Amount: c.FeeAmount, Currency: c.Currency, DecimalPlaces: c.DecimalPlaces}
}

// Exact reports that the share divided evenly, or that a bound decided the fee
// and there was nothing to divide.
func (c Charge) Exact() bool { return c.RemainderNumerator == 0 }

// EntryKind is the direction of one movement.
type EntryKind string

// The two directions money moves on a wallet. They are read from the wallet's
// side: a deposit raises the balance and a withdrawal lowers it, whether the
// operation around them was a transfer, a reversal or a deposit of its own.
const (
	// EntryDeposit raised the balance.
	EntryDeposit EntryKind = "deposit"
	// EntryWithdraw lowered it.
	EntryWithdraw EntryKind = "withdraw"
)

// Flag is a yes-or-no column held as the integer 0 or 1, and it carries how that
// is written and how it is read back.
//
// The column is an integer, and a Go bool is not what a driver accepts for one:
// a driver that has been told its parameter is a small integer refuses a bool
// outright, and one told the opposite refuses an integer. So the Go value spells
// its own column -- which is the same arrangement Amount has with the column that
// holds money, and for the same reason: a value that says what it writes cannot
// be spelled differently by an engine.
//
// Reading is wider than writing on purpose. A yes-or-no comes back as an
// integer, a boolean, the text of either or the bytes of any of them depending
// on the engine and on how the table was created, and this is the one place that
// is flattened.
type Flag bool

// Value writes the flag as the integer the column holds.
func (f Flag) Value() (driver.Value, error) {
	if f {
		return int64(1), nil
	}
	return int64(0), nil
}

// Scan reads the flag back from whatever an engine answers with.
//
// The engines disagree, and this is where that is flattened: an integer, a
// boolean, the text of either, and the bytes of any of them all mean the same
// thing. Anything else is refused rather than read as false, because a column
// this package cannot read is a column whose meaning it would be inventing.
func (f *Flag) Scan(value any) error {
	switch v := value.(type) {
	case nil:
		*f = false
		return nil
	case bool:
		*f = Flag(v)
		return nil
	case int64:
		*f = v != 0
		return nil
	case int32:
		*f = v != 0
		return nil
	case int16:
		*f = v != 0
		return nil
	case int:
		*f = v != 0
		return nil
	case float64:
		*f = v != 0
		return nil
	case []byte:
		return f.scanText(string(v))
	case string:
		return f.scanText(v)
	}
	return fmt.Errorf("wallet: a yes-or-no column answered with a %T", value)
}

// scanText reads a flag an engine answered as text.
func (f *Flag) scanText(text string) error {
	switch strings.ToLower(strings.TrimSpace(text)) {
	case "1", "t", "true", "y", "yes", "on":
		*f = true
		return nil
	case "0", "f", "false", "n", "no", "off", "":
		*f = false
		return nil
	}
	return fmt.Errorf("wallet: a yes-or-no column answered %q", text)
}

// Entry is one movement of money on one wallet, and the ledger is the sum of
// them.
//
// Rows are appended and never changed. A movement that turned out to be wrong
// is undone by appending the opposite movement under an operation that names
// the one it reverses, so what happened stays readable after it is undone --
// which a status column that is rewritten in place cannot do.
type Entry struct {
	model.Model[Entry]

	// ID is the identifier, generated by the application.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to, written from the Grant.
	TenantID string `db:"tenant_id"`

	// OperationID is the request this movement was part of. A transfer writes
	// two entries under one operation.
	OperationID string `db:"operation_id"`

	// WalletID is the wallet that moved.
	WalletID string `db:"wallet_id"`

	// Kind is the direction.
	Kind EntryKind `db:"kind"`

	// Sequence is this entry's position in its wallet's ledger, counting from
	// one and never repeating. It is what a statement is ordered and paged by,
	// and a unique index holds it: two entries at one position would be a
	// ledger that lost a write without saying so.
	Sequence int64 `db:"sequence"`

	// Position is this entry's place within its own operation, counting from
	// zero. A transfer writes the wallet that pays at zero and the wallet that
	// is paid at one, so a receipt reads the same way when it is produced and
	// when it is replayed.
	Position int `db:"position"`

	// Amount is how much moved, in the wallet's minor units, and it is always
	// positive: the direction is Kind's to carry, so that a sum over the
	// history cannot be made to mean the opposite of what it says by a sign
	// somebody wrote into an amount.
	Amount Amount `db:"amount"`

	// BalanceAfter is what the wallet held once this movement was applied.
	//
	// Written because a statement a person reads is a running balance, and
	// recomputing one means replaying every earlier row. It is also what makes
	// the ledger check itself: the last entry of a wallet has to equal the
	// wallet's balance column. A pending entry moved nothing, so it records the
	// balance it did not change, and that identity holds down the whole page.
	BalanceAfter Amount `db:"balance_after"`

	// Settled reports that this movement counted: that the balance moved by
	// exactly this amount, in this direction, when the row was written.
	//
	// A pending entry is false, and it is the record of money that was proposed
	// and has not moved. It is written once like every other column here and is
	// never flipped afterwards -- confirming appends the settled entry beside
	// it, under an operation that names the one it settles, so a wallet's
	// history says what was asked for and then what happened rather than
	// showing only the second of the two.
	Settled Flag `db:"settled"`

	// Meta is what the application attached to this leg in particular, and it
	// is empty where the leg said nothing the operation did not.
	//
	// A movement with one leg carries its facts on the operation, because there
	// they are the request's. A movement with two or twenty carries them here as
	// well, because a basket's line and the payment it is part of are different
	// facts and a receipt that showed one for the other would be a receipt about
	// something else.
	Meta Meta `db:"meta"`

	// CreatedAt is when the movement was written, in UTC.
	CreatedAt time.Time `db:"created_at"`
}

// Entries returns the configured model for the entries table.
func Entries(db *data.DB) *model.Model[Entry] {
	m := model.NewModel[Entry](entriesTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// Signed is the movement as it adds to a balance: positive for a deposit,
// negative for a withdrawal, and zero where it has not settled.
//
// It is how a sum over a history is taken, and it is a method rather than a
// column so that the sign exists in exactly one place. The zero is the same
// decision: a pending entry adds nothing to a balance, so the sum of this over
// a wallet's whole history is the balance column, exactly as it was before
// anything could be pending. What the amount of a pending row means is what was
// proposed, and Amount is where that is read.
func (e Entry) Signed() Amount {
	if !e.Settled {
		return 0
	}
	if e.Kind == EntryWithdraw {
		return -e.Amount
	}
	return e.Amount
}

// The refusals this package answers with. Each one is a different thing for the
// caller to do, which is why they are separate values rather than one error
// with a message.
var (
	// ErrNotFound is returned when no row matches, including when the row
	// exists in another tenant. The two cases are deliberately
	// indistinguishable.
	ErrNotFound = errors.New("wallet: record not found")

	// ErrInsufficientFunds is returned when a withdrawal would take a balance
	// past what the wallet may hold: below zero, or below the negative of its
	// credit limit where it has one. It is the answer of the statement that
	// would have moved the money, not of a check that ran before it.
	ErrInsufficientFunds = errors.New("wallet: the balance and the credit limit are not enough for this withdrawal")

	// ErrCreditNegative is returned when a credit limit is written as a
	// negative number. The limit is how far below zero the wallet may go, so it
	// is a magnitude; a negative one would read as a balance the wallet has to
	// keep, which is a different rule nobody asked for.
	ErrCreditNegative = errors.New("wallet: a credit limit is how far below zero a wallet may go, and cannot be negative")

	// ErrCreditBelowBalance is returned when lowering a credit limit would
	// leave the wallet already past it. The refusal comes from the statement
	// that would have written it, so a balance that moved in between changes
	// the answer -- and no wallet is left in a state no rule would have
	// allowed it to reach.
	ErrCreditBelowBalance = errors.New("wallet: the balance is already further below zero than the new credit limit allows")

	// ErrCurrencyMismatch is returned when a transfer names two wallets that
	// are not counted the same way -- a different currency, or the same
	// currency at a different scale. Moving between them needs a rate, and a
	// rate comes from a RateProvider the application supplies.
	ErrCurrencyMismatch = errors.New("wallet: the two wallets are not counted the same way, which needs a rate")

	// ErrSameWallet is returned when a transfer names one wallet twice. It
	// would be a pair of entries that cancel, which is a statement that says
	// something happened when nothing did.
	ErrSameWallet = errors.New("wallet: a transfer needs two different wallets")

	// ErrAlreadyReversed is returned when an operation has already been
	// undone. The refusal comes from a unique index, so two concurrent
	// reversals of one operation cannot both succeed.
	ErrAlreadyReversed = errors.New("wallet: this operation has already been reversed")

	// ErrNotReversible is returned when the operation named is itself a
	// reversal. Undoing an undo is a new operation with its own reason, not a
	// second reversal of the same movement.
	ErrNotReversible = errors.New("wallet: a reversal cannot itself be reversed")

	// ErrNotSettled is returned when a reversal names an operation that never
	// moved anything. There is nothing to undo: what a pending operation wrote
	// is a record of what was proposed, and appending its opposite would take
	// out money that was never put in.
	ErrNotSettled = errors.New("wallet: that operation has not moved any money, so there is nothing to undo")

	// ErrNotPending is returned when a confirmation names an operation that has
	// no pending entry. Everything it wrote already counts, and confirming it
	// again would move the money a second time.
	ErrNotPending = errors.New("wallet: that operation has nothing waiting to be confirmed")

	// ErrAlreadyConfirmed is returned when an operation has already been made
	// to count. The refusal comes from a unique index, so two concurrent
	// confirmations of one operation cannot both succeed.
	ErrAlreadyConfirmed = errors.New("wallet: this operation has already been confirmed")

	// ErrWalletExists is returned when the holder already has a wallet under
	// this slug.
	ErrWalletExists = errors.New("wallet: this holder already has a wallet with that slug")

	// ErrOperationConflict is returned when an idempotency key names a request
	// that asked for something else. Two different requests under one key
	// cannot both be that key's answer, so neither is guessed at.
	ErrOperationConflict = errors.New("wallet: that idempotency key belongs to a different request")

	// ErrConcurrencyConflict is returned when the engine refused a movement as
	// a serialization failure or a deadlock, and retrying it did not get past
	// that. It is a distinct answer because it is the one the caller can act
	// on: nothing was written, the request is still valid, and sending it again
	// under the same idempotency key is safe.
	ErrConcurrencyConflict = errors.New("wallet: the engine refused this movement as a conflict with another transaction, and the retries did not clear it")

	// ErrWalletFrozen is returned when a movement names a wallet whose ledger
	// no longer explains its balance. The refusal comes from the statement that
	// would have moved the money, so a wallet frozen between the read and the
	// write is refused at the write.
	ErrWalletFrozen = errors.New("wallet: this wallet is frozen because its ledger and its balance disagree, and Rebuild is what closes that")

	// ErrWalletNotFrozen is returned when a rebuild names a wallet that is not
	// frozen. The freeze is what holds the balance and the ledger still while
	// the difference is measured and written, so a rebuild without one would be
	// an adjustment computed from numbers that can move underneath it.
	ErrWalletNotFrozen = errors.New("wallet: this wallet is not frozen, so a rebuild would adjust it by a difference that can still change")

	// ErrLedgerMoved is returned when a wallet moved while its ledger was being
	// read. What the scan concluded is about a wallet that no longer exists in
	// that state, so it is reported rather than acted on.
	ErrLedgerMoved = errors.New("wallet: the wallet moved while its ledger was being read, so the reconciliation is about a state it has left")

	// ErrLedgerBalanced is returned when a rebuild names a wallet whose ledger
	// already explains its balance. There is no difference to close, and an
	// adjustment of nothing would be a row in the ledger saying something
	// happened when nothing did.
	ErrLedgerBalanced = errors.New("wallet: this wallet's ledger already adds up to its balance, so there is nothing to adjust")

	// ErrUnsupportedDialect is returned when the handle speaks an engine this
	// package does not verify. The guard on a withdrawal is a predicate on an
	// update, and what an update sees of a row another transaction is changing
	// is the engine's answer rather than this package's -- so an engine no test
	// here runs against is an engine whose answer nobody has read.
	ErrUnsupportedDialect = errors.New("wallet: this package is verified on PostgreSQL and SQLite, and refuses an engine its suite has never run against")
)

// Resource is the list of fields one Wallet is allowed to answer with.
//
// A declared list rather than the entity itself. An encoder handed the entity
// answers with whatever fields it happens to have, including the ones somebody
// adds later without ever opening the handler -- and TenantID is exactly such a
// field: it names another customer's identifier and belongs in no response.
type Resource struct {
	id            string
	holderID      string
	slug          string
	name          string
	description   string
	meta          Meta
	currency      Currency
	decimalPlaces int
	balance       Amount
	creditLimit   Amount
	createdAt     time.Time
}

// NewResource snapshots one wallet for the response.
func NewResource(record Wallet) Resource {
	return Resource{
		id:            record.ID,
		holderID:      record.HolderID,
		slug:          record.Slug,
		name:          record.Name,
		description:   record.Description,
		meta:          record.Meta,
		currency:      record.Currency,
		decimalPlaces: record.DecimalPlaces,
		balance:       record.Balance,
		creditLimit:   record.CreditLimit,
		createdAt:     record.CreatedAt,
	}
}

func resourceFromPointer(record *Wallet) Resource {
	if record == nil {
		return Resource{}
	}
	return NewResource(*record)
}

// ToArray returns the fields that may leave, by name.
//
// The balance leaves twice: once as the integer the ledger is kept in, and once
// as the decimal a person reads. A client that computes anything reads
// balance_minor, one that prints reads balance, and neither has to know the
// scale to do its half -- which is there anyway, for the one that does.
//
// The credit limit leaves beside it, in both spellings, because a balance that
// may go below zero is not readable without the number that says how far. It is
// a magnitude and never a negative: what it bounds is the negative side.
func (r Resource) ToArray() map[string]any {
	return map[string]any{
		"id":                 r.id,
		"holder_id":          r.holderID,
		"slug":               r.slug,
		"name":               r.name,
		"description":        r.description,
		"meta":               map[string]string(r.meta),
		"currency":           string(r.currency),
		"decimal_places":     r.decimalPlaces,
		"balance_minor":      int64(r.balance),
		"balance":            r.balance.Format(r.decimalPlaces),
		"credit_limit_minor": int64(r.creditLimit),
		"credit_limit":       r.creditLimit.Format(r.decimalPlaces),
		"created_at":         r.createdAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields at the top level of the response.
// Nothing does here, and a resource that has nothing to add says so by
// answering nil.
func (r Resource) With() map[string]any { return nil }

// Collection is a page of wallets as one response.
type Collection struct {
	records []Resource
	// cursor is what the next page asks for, empty when this page is the last
	// one. It goes beside the items rather than inside them: it describes the
	// answer, not the things answered with.
	cursor string
}

// NewCollection wraps a page of wallets for the response. The cursor is what
// the next request passes back, and is empty when there is no next page.
func NewCollection(records []Wallet, cursor string) Collection {
	resources := make([]Resource, 0, len(records))
	for _, record := range records {
		resources = append(resources, NewResource(record))
	}
	return Collection{records: resources, cursor: cursor}
}

// collectionFromPointers takes the Model-backed rows returned by a terminal
// and snapshots only what the response reads. The public constructor keeps its
// value-based API for callers that build resources without touching storage.
func collectionFromPointers(records []*Wallet, cursor string) Collection {
	resources := make([]Resource, 0, len(records))
	for _, record := range records {
		if record != nil {
			resources = append(resources, NewResource(*record))
		}
	}
	return Collection{records: resources, cursor: cursor}
}

// ToArray returns the page under a single key, so that the shape of the
// response does not change when a second key is added beside it.
func (c Collection) ToArray() map[string]any {
	items := make([]map[string]any, 0, len(c.records))
	for _, record := range c.records {
		items = append(items, record.ToArray())
	}
	return map[string]any{"items": items}
}

// With returns the cursor of the next page, and nothing when there is none.
func (c Collection) With() map[string]any {
	if c.cursor == "" {
		return nil
	}
	return map[string]any{"next_cursor": c.cursor}
}

// ConversionResource is the list of fields one conversion may answer with.
//
// Every number the arithmetic used is here, and that is the point: a client
// that wants to check what it was charged multiplies the amount that left by
// the numerator and by ten to the target's scale, and finds the amount that
// arrived times the denominator times ten to the source's scale, plus the
// remainder. Nothing it needs for that is missing and nothing it needs is
// somewhere else.
type ConversionResource struct {
	operationID          string
	from                 Money
	to                   Money
	rate                 Rate
	rounding             Rounding
	remainderNumerator   int64
	remainderDenominator int64
	createdAt            time.Time
}

// NewConversionResource snapshots one conversion for the response.
func NewConversionResource(record Conversion) ConversionResource {
	return ConversionResource{
		operationID:          record.OperationID,
		from:                 record.From(),
		to:                   record.To(),
		rate:                 record.Rate(),
		rounding:             record.Rounding,
		remainderNumerator:   record.RemainderNumerator,
		remainderDenominator: record.RemainderDenominator,
		createdAt:            record.CreatedAt,
	}
}

// ToArray returns the fields that may leave, by name.
//
// The rate leaves twice, as the two integers and as the pair written out. A
// client that recomputes reads the integers, one that prints reads the string,
// and neither has to derive the other's form -- which is the same reason a
// balance leaves as both an integer and a decimal.
func (r ConversionResource) ToArray() map[string]any {
	return map[string]any{
		"operation_id":          r.operationID,
		"from_currency":         string(r.from.Currency),
		"from_decimal_places":   r.from.DecimalPlaces,
		"from_amount_minor":     int64(r.from.Amount),
		"from_amount":           r.from.Amount.Format(r.from.DecimalPlaces),
		"to_currency":           string(r.to.Currency),
		"to_decimal_places":     r.to.DecimalPlaces,
		"to_amount_minor":       int64(r.to.Amount),
		"to_amount":             r.to.Amount.Format(r.to.DecimalPlaces),
		"rate":                  r.rate.String(),
		"rate_numerator":        r.rate.Numerator,
		"rate_denominator":      r.rate.Denominator,
		"rounding":              string(r.rounding),
		"remainder_numerator":   r.remainderNumerator,
		"remainder_denominator": r.remainderDenominator,
		"exact":                 r.remainderNumerator == 0,
		"quoted_at":             r.rate.QuotedAt.UTC().Format(time.RFC3339),
		"created_at":            r.createdAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields, and nothing does.
func (r ConversionResource) With() map[string]any { return nil }

// ChargeResource is the list of fields one charge may answer with.
//
// Every number the arithmetic used is here, for the reason the conversion's
// are: a client that wants to check what it was charged multiplies the base by
// the numerator and finds the fee times the denominator plus the remainder, or
// reads the bound that decided instead. Nothing it needs for that is missing and
// nothing it needs is somewhere else.
type ChargeResource struct {
	operationID          string
	currency             Currency
	decimalPlaces        int
	requested            Amount
	discount             Amount
	base                 Amount
	schedule             FeeSchedule
	fee                  Amount
	rounding             Rounding
	remainderNumerator   int64
	remainderDenominator int64
	createdAt            time.Time
}

// NewChargeResource snapshots one charge for the response.
func NewChargeResource(record Charge) ChargeResource {
	return ChargeResource{
		operationID:          record.OperationID,
		currency:             record.Currency,
		decimalPlaces:        record.DecimalPlaces,
		requested:            record.RequestedAmount,
		discount:             record.Discount,
		base:                 record.BaseAmount,
		schedule:             record.Schedule(),
		fee:                  record.FeeAmount,
		rounding:             record.Rounding,
		remainderNumerator:   record.RemainderNumerator,
		remainderDenominator: record.RemainderDenominator,
		createdAt:            record.CreatedAt,
	}
}

// ToArray returns the fields that may leave, by name.
//
// Each amount leaves twice, as the integer the ledger is kept in and as the
// decimal a person reads, which is the same arrangement a balance has and for
// the same reason.
func (r ChargeResource) ToArray() map[string]any {
	return map[string]any{
		"operation_id":           r.operationID,
		"currency":               string(r.currency),
		"decimal_places":         r.decimalPlaces,
		"requested_amount_minor": int64(r.requested),
		"requested_amount":       r.requested.Format(r.decimalPlaces),
		"discount_minor":         int64(r.discount),
		"discount":               r.discount.Format(r.decimalPlaces),
		"base_amount_minor":      int64(r.base),
		"base_amount":            r.base.Format(r.decimalPlaces),
		"fee_minor":              int64(r.fee),
		"fee":                    r.fee.Format(r.decimalPlaces),
		"fee_numerator":          r.schedule.Numerator,
		"fee_denominator":        r.schedule.Denominator,
		"fee_minimum_minor":      int64(r.schedule.Minimum),
		"fee_maximum_minor":      int64(r.schedule.Maximum),
		"fee_deductible":         r.schedule.Deductible,
		"fee_wallet_id":          r.schedule.WalletID,
		"rounding":               string(r.rounding),
		"remainder_numerator":    r.remainderNumerator,
		"remainder_denominator":  r.remainderDenominator,
		"exact":                  r.remainderNumerator == 0,
		"created_at":             r.createdAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields, and nothing does.
func (r ChargeResource) With() map[string]any { return nil }

// EntryResource is the list of fields one ledger entry may answer with.
type EntryResource struct {
	id            string
	operationID   string
	operationKind OperationKind
	walletID      string
	kind          EntryKind
	amount        Amount
	balanceAfter  Amount
	settled       Flag
	meta          Meta
	decimalPlaces int
	createdAt     time.Time
}

// NewEntryResource snapshots one entry for the response, read at the scale of
// the wallet it moved and under the operation that wrote it.
//
// The operation's kind travels with the movement because the movement alone
// does not say what happened: a withdrawal is a withdrawal whether it paid
// somebody, was undone, or was converted into another currency, and a statement
// where those read the same is a statement that hides the exchange inside the
// transfers. An empty kind is an entry whose operation was not loaded, which is
// what a caller building one resource by hand has.
func NewEntryResource(record Entry, decimalPlaces int, kind OperationKind) EntryResource {
	return EntryResource{
		id:            record.ID,
		operationID:   record.OperationID,
		operationKind: kind,
		walletID:      record.WalletID,
		kind:          record.Kind,
		amount:        record.Amount,
		balanceAfter:  record.BalanceAfter,
		settled:       record.Settled,
		meta:          record.Meta,
		decimalPlaces: decimalPlaces,
		createdAt:     record.CreatedAt,
	}
}

// ToArray returns the fields that may leave, by name.
//
// Whether the movement settled leaves with it, because the amount alone does
// not say whether it counted: a client that added up the amounts of a page and
// found the balance would be a client that was right until the first pending
// row.
func (r EntryResource) ToArray() map[string]any {
	return map[string]any{
		"id":                  r.id,
		"operation_id":        r.operationID,
		"operation_kind":      string(r.operationKind),
		"wallet_id":           r.walletID,
		"kind":                string(r.kind),
		"amount_minor":        int64(r.amount),
		"amount":              r.amount.Format(r.decimalPlaces),
		"balance_after_minor": int64(r.balanceAfter),
		"balance_after":       r.balanceAfter.Format(r.decimalPlaces),
		"settled":             bool(r.settled),
		"meta":                map[string]string(r.meta),
		"created_at":          r.createdAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields, and nothing does.
func (r EntryResource) With() map[string]any { return nil }

// EntryCollection is a page of ledger entries as one response.
type EntryCollection struct {
	records     []EntryResource
	conversions []ConversionResource
	charges     []ChargeResource
	cursor      string
}

// NewEntryCollection wraps a page of one wallet's ledger for the response.
//
// It takes the statement rather than the entries, because an entry is not
// readable on its own: the scale it is written at belongs to the wallet, and
// what it was part of belongs to the operation. Both travel in the statement,
// so this is one argument instead of three that could disagree.
//
// The rates and the charges go beside the items and not inside them. Each
// belongs to an operation, an operation writes an entry on each of two or three
// wallets, and repeating one on every entry would be repeating one fact until
// two copies of it could differ.
func NewEntryCollection(statement Statement, cursor string) EntryCollection {
	resources := make([]EntryResource, 0, len(statement.Entries))
	for _, record := range statement.Entries {
		if record != nil {
			resources = append(resources, NewEntryResource(*record, statement.Wallet.DecimalPlaces, statement.Operations[record.OperationID].Kind))
		}
	}

	// In the order the entries name them, so a page reads the same twice.
	seen := make(map[string]bool, len(statement.Entries))
	rates := make([]ConversionResource, 0, len(statement.Conversions))
	charged := make([]ChargeResource, 0, len(statement.Charges))
	for _, record := range statement.Entries {
		if record == nil || seen[record.OperationID] {
			continue
		}
		seen[record.OperationID] = true
		if converted, ok := statement.Conversions[record.OperationID]; ok {
			rates = append(rates, NewConversionResource(converted))
		}
		if cost, ok := statement.Charges[record.OperationID]; ok {
			charged = append(charged, NewChargeResource(cost))
		}
	}
	return EntryCollection{records: resources, conversions: rates, charges: charged, cursor: cursor}
}

// ToArray returns the page under a single key.
func (c EntryCollection) ToArray() map[string]any {
	items := make([]map[string]any, 0, len(c.records))
	for _, record := range c.records {
		items = append(items, record.ToArray())
	}
	return map[string]any{"items": items}
}

// With returns the cursor of the next page, the rates the page's exchanges were
// made at and what its payments were charged, and omits any of them when there
// is none.
func (c EntryCollection) With() map[string]any {
	beside := map[string]any{}
	if c.cursor != "" {
		beside["next_cursor"] = c.cursor
	}
	if len(c.conversions) > 0 {
		rates := make([]map[string]any, 0, len(c.conversions))
		for _, conversion := range c.conversions {
			rates = append(rates, conversion.ToArray())
		}
		beside["conversions"] = rates
	}
	if len(c.charges) > 0 {
		costs := make([]map[string]any, 0, len(c.charges))
		for _, charge := range c.charges {
			costs = append(costs, charge.ToArray())
		}
		beside["charges"] = costs
	}
	if len(beside) == 0 {
		return nil
	}
	return beside
}

// Receipt is what a movement of money answers with.
//
// It carries the operation and every entry the operation wrote, so a transfer
// answers about both wallets in one value and a caller never has to ask a
// second question to learn what its own request did.
type Receipt struct {
	// Operation is the request that was recorded.
	Operation Operation
	// Entries are the movements it wrote, in the order they were applied.
	Entries []Entry
	// Conversion is the rate the operation applied, and nil where it applied
	// none. Only an exchange has one.
	Conversion *Conversion
	// Charge is what the operation charged beyond the money it moved, and nil
	// where it charged nothing. Only a payment between two wallets has one.
	Charge *Charge
	// Purchases are the lines a basket was made of, in the order they were paid
	// for, and empty on every operation that bought nothing.
	//
	// They are here rather than under Charge because a basket is not one payment
	// between two wallets: each line has its own price, its own discount, its
	// own fee and its own pair of wallets, and a single charge row for the lot
	// would be one number where there are six.
	Purchases []Purchase
	// Replayed reports that this operation had already run under the same
	// idempotency key, and that nothing moved on this call. The money in the
	// receipt is the money the first call moved, at the rate the first call
	// was quoted.
	Replayed bool
}

// Pending reports that this operation is on the record and has not moved any
// money: every entry it wrote is waiting to be confirmed.
//
// A receipt with no entries at all is not pending. There is nothing waiting in
// it, and answering that there is would be answering about a movement that does
// not exist.
func (r Receipt) Pending() bool {
	for _, entry := range r.Entries {
		if entry.Settled {
			return false
		}
	}
	return len(r.Entries) > 0
}

// ReceiptResource is what a receipt may answer with.
type ReceiptResource struct {
	operationID    string
	kind           OperationKind
	idempotencyKey string
	reverses       string
	confirms       string
	pending        bool
	replayed       bool
	meta           Meta
	entries        []EntryResource
	conversion     *ConversionResource
	charge         *ChargeResource
	purchases      []PurchaseResource
	createdAt      time.Time
}

// NewReceiptResource snapshots a receipt for the response.
//
// The scales are per wallet and not one for the whole receipt, because an
// exchange writes two entries counted differently: rendering both at one scale
// moves the decimal point on one of them, which is a receipt that reports a
// number nobody was charged. A wallet the map does not name renders as the
// integer, which is worse to read and impossible to misread.
func NewReceiptResource(receipt Receipt, places map[string]int) ReceiptResource {
	entries := make([]EntryResource, 0, len(receipt.Entries))
	for _, entry := range receipt.Entries {
		entries = append(entries, NewEntryResource(entry, places[entry.WalletID], receipt.Operation.Kind))
	}

	var conversion *ConversionResource
	if receipt.Conversion != nil {
		snapshot := NewConversionResource(*receipt.Conversion)
		conversion = &snapshot
	}

	var charge *ChargeResource
	if receipt.Charge != nil {
		snapshot := NewChargeResource(*receipt.Charge)
		charge = &snapshot
	}

	purchases := make([]PurchaseResource, 0, len(receipt.Purchases))
	for _, purchase := range receipt.Purchases {
		purchases = append(purchases, NewPurchaseResource(purchase))
	}
	return ReceiptResource{
		operationID:    receipt.Operation.ID,
		kind:           receipt.Operation.Kind,
		idempotencyKey: receipt.Operation.IdempotencyKey,
		reverses:       receipt.Operation.Reverses(),
		confirms:       receipt.Operation.Confirms(),
		pending:        receipt.Pending(),
		replayed:       receipt.Replayed,
		meta:           receipt.Operation.Meta,
		entries:        entries,
		conversion:     conversion,
		charge:         charge,
		purchases:      purchases,
		createdAt:      receipt.Operation.CreatedAt,
	}
}

// ToArray returns the fields that may leave, by name.
//
// The conversion is present on an exchange and null on everything else, and the
// charge on a payment that discounted or charged and null on everything else --
// present rather than absent, because a key that appears and disappears is a key
// a client reads with a branch it forgets to write.
func (r ReceiptResource) ToArray() map[string]any {
	entries := make([]map[string]any, 0, len(r.entries))
	for _, entry := range r.entries {
		entries = append(entries, entry.ToArray())
	}

	var conversion any
	if r.conversion != nil {
		conversion = r.conversion.ToArray()
	}

	var charge any
	if r.charge != nil {
		charge = r.charge.ToArray()
	}

	purchases := make([]map[string]any, 0, len(r.purchases))
	for _, purchase := range r.purchases {
		purchases = append(purchases, purchase.ToArray())
	}
	return map[string]any{
		"operation_id":    r.operationID,
		"kind":            string(r.kind),
		"idempotency_key": r.idempotencyKey,
		"reverses":        r.reverses,
		"confirms":        r.confirms,
		"pending":         r.pending,
		"replayed":        r.replayed,
		"meta":            map[string]string(r.meta),
		"entries":         entries,
		"conversion":      conversion,
		"charge":          charge,
		"purchases":       purchases,
		"created_at":      r.createdAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields, and nothing does.
func (r ReceiptResource) With() map[string]any { return nil }
