// Code generated by aru model:build from model.go. DO NOT EDIT.

package wallet

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Operations starts a query on the table of Operation, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Operations(db model.DB) *OperationQuery { return &OperationQuery{b: operationTable.Query(db)} }

// OperationQuery is a query on the table of Operation.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Operation rows or a value; there is
// no way to run one without a Grant.
type OperationQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *OperationQuery) Base() *model.Builder { return q.b }

// New returns an empty Operation on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *OperationQuery) New() (*Operation, error) {
	e, err := q.b.NewModelInstance(nil)
	return operationOf(e), err
}

// OperationCollection is rows of Operation, as a query returns them.
type OperationCollection []*Operation

// OperationCollectionOf converts rows of the table of Operation. A nil input is a nil
// collection.
func OperationCollectionOf(rows model.Rows) OperationCollection {
	if rows == nil {
		return nil
	}
	out := make(OperationCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Operation)
	}
	return out
}

func operationOf(e model.Entity) *Operation {
	row, _ := e.(*Operation)
	return row
}

// operationColumn turns a closure over OperationQuery into one over the core builder, so
// passing func(*OperationQuery) where a column goes adds a parenthesised group.
func operationColumn(column any) any {
	if group, ok := column.(func(*OperationQuery)); ok {
		return func(b *model.Builder) { group(&OperationQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *OperationQuery) Clone() *OperationQuery { return &OperationQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*OperationQuery) in place of the column adds a group.
func (q *OperationQuery) Where(column any, args ...any) *OperationQuery {
	q.b.Where(operationColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*OperationQuery) in place of the column adds a group.
func (q *OperationQuery) OrWhere(column any, args ...any) *OperationQuery {
	q.b.OrWhere(operationColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *OperationQuery) WhereNot(column any, args ...any) *OperationQuery {
	q.b.WhereNot(operationColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *OperationQuery) OrWhereNot(column any, args ...any) *OperationQuery {
	q.b.OrWhereNot(operationColumn(column), args...)
	return q
}

func (q *OperationQuery) WhereIn(column any, values []any) *OperationQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *OperationQuery) WhereNotIn(column any, values []any) *OperationQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *OperationQuery) WhereNull(columns ...any) *OperationQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *OperationQuery) WhereNotNull(columns ...any) *OperationQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *OperationQuery) WhereBetween(column any, from, to any) *OperationQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *OperationQuery) WhereColumn(first any, args ...any) *OperationQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *OperationQuery) WhereKey(id any) *OperationQuery {
	q.b.WhereKey(id)
	return q
}

func (q *OperationQuery) WhereExists(callback func(*query.Builder)) *OperationQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *OperationQuery) WhereNotExists(callback func(*query.Builder)) *OperationQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *OperationQuery) WhereHas(relation string, callback func(*query.Builder)) *OperationQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *OperationQuery) OrWhereHas(relation string, callback func(*query.Builder)) *OperationQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *OperationQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *OperationQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *OperationQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *OperationQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *OperationQuery) WhereRelation(relation string, column any, args ...any) *OperationQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *OperationQuery) OrWhereRelation(relation string, column any, args ...any) *OperationQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *OperationQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *OperationQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *OperationQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *OperationQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *OperationQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *OperationQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *OperationQuery) OrHas(relation, operator string, count int) *OperationQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *OperationQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *OperationQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *OperationQuery) OrDoesntHave(relation string) *OperationQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *OperationQuery) Select(columns ...any) *OperationQuery {
	q.b.Select(columns...)
	return q
}

func (q *OperationQuery) AddSelect(columns ...any) *OperationQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *OperationQuery) SelectRaw(expression string, bindings ...any) *OperationQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *OperationQuery) Join(table any, first any, args ...any) *OperationQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *OperationQuery) GroupBy(groups ...any) *OperationQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *OperationQuery) OrderBy(column any, direction ...string) *OperationQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *OperationQuery) OrderByDesc(column any) *OperationQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *OperationQuery) Latest(column ...string) *OperationQuery {
	q.b.Latest(column...)
	return q
}

func (q *OperationQuery) Oldest(column ...string) *OperationQuery {
	q.b.Oldest(column...)
	return q
}

func (q *OperationQuery) Limit(value int) *OperationQuery {
	q.b.Limit(value)
	return q
}

func (q *OperationQuery) Offset(value int) *OperationQuery {
	q.b.Offset(value)
	return q
}

func (q *OperationQuery) ForPage(page, perPage int) *OperationQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *OperationQuery) With(relations ...string) *OperationQuery {
	q.b.With(relations...)
	return q
}

func (q *OperationQuery) WithCount(relations ...string) *OperationQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *OperationQuery) WithExists(relation string) *OperationQuery {
	q.b.WithExists(relation)
	return q
}

func (q *OperationQuery) WithSum(relation, column string) *OperationQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *OperationQuery) WithAvg(relation, column string) *OperationQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *OperationQuery) WithMin(relation, column string) *OperationQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *OperationQuery) WithMax(relation, column string) *OperationQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *OperationQuery) Without(relations ...string) *OperationQuery {
	q.b.Without(relations...)
	return q
}

func (q *OperationQuery) WithoutGlobalScope(identifier string) *OperationQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *OperationQuery) WithoutGlobalScopes(identifiers ...string) *OperationQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *OperationQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (OperationCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return OperationCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *OperationQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Operation, error) {
	e, err := q.b.First(ctx, g, columns...)
	return operationOf(e), err
}

func (q *OperationQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Operation, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return operationOf(e), err
}

func (q *OperationQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Operation, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return operationOf(e), err
}

func (q *OperationQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Operation, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return operationOf(e), err
}

func (q *OperationQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Operation, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return operationOf(e), err
}

func (q *OperationQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Operation, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return operationOf(e), err
}

func (q *OperationQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Operation, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return operationOf(e), err
}

func (q *OperationQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Operation, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return operationOf(e), err
}

func (q *OperationQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (OperationCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return OperationCollectionOf(rows), err
}

func (q *OperationQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Operation, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return operationOf(e), err
}

func (q *OperationQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Operation, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return operationOf(e), err
}

func (q *OperationQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Operation, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return operationOf(e), err
}

func (q *OperationQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Operation, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return operationOf(e), err
}

func (q *OperationQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (OperationCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return OperationCollectionOf(rows), meta, err
}

func (q *OperationQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (OperationCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return OperationCollectionOf(rows), meta, err
}

func (q *OperationQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (OperationCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return OperationCollectionOf(rows), meta, err
}

func (q *OperationQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(OperationCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(OperationCollectionOf(rows), page)
	})
}

func (q *OperationQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Operation, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(operationOf(e), index)
	})
}

func (q *OperationQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Operation, error] {
	return func(yield func(*Operation, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(operationOf(e), err) {
				return
			}
		}
	}
}

func (q *OperationQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *OperationQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *OperationQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *OperationQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *OperationQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *OperationQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *OperationQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *OperationQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *OperationQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *OperationQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *OperationQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *OperationQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *OperationQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *OperationQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *OperationQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *OperationQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *OperationQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *OperationQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *OperationQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c OperationCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c OperationCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c OperationCollection) Find(key any) *Operation { return operationOf(c.Rows().Find(key)) }

func (c OperationCollection) FindOrFail(key any) (*Operation, error) {
	e, err := c.Rows().FindOrFail(key)
	return operationOf(e), err
}

func (c OperationCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c OperationCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c OperationCollection) Only(keys ...any) OperationCollection {
	return OperationCollectionOf(c.Rows().Only(keys...))
}

func (c OperationCollection) Except(keys ...any) OperationCollection {
	return OperationCollectionOf(c.Rows().Except(keys...))
}

func (c OperationCollection) Unique() OperationCollection {
	return OperationCollectionOf(c.Rows().Unique())
}

func (c OperationCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c OperationCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c OperationCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c OperationCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (OperationCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return OperationCollectionOf(rows), err
}

func (c OperationCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Operation; it shadows the untyped one the
// embedded model promotes.
func (row *Operation) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Operation, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return operationOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Operation) Replicate(except ...string) (*Operation, error) {
	e, err := row.Model.Replicate(except...)
	return operationOf(e), err
}
