// Code generated by aru model:build from purchase.go. DO NOT EDIT.

package wallet

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Purchases starts a query on the table of Purchase, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Purchases(db model.DB) *PurchaseQuery { return &PurchaseQuery{b: purchaseTable.Query(db)} }

// PurchaseQuery is a query on the table of Purchase.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Purchase rows or a value; there is
// no way to run one without a Grant.
type PurchaseQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of purchase.go -- and for the
// factory, which builds rows through it.
func (q *PurchaseQuery) Base() *model.Builder { return q.b }

// New returns an empty Purchase on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *PurchaseQuery) New() (*Purchase, error) {
	e, err := q.b.NewModelInstance(nil)
	return purchaseOf(e), err
}

// PurchaseCollection is rows of Purchase, as a query returns them.
type PurchaseCollection []*Purchase

// PurchaseCollectionOf converts rows of the table of Purchase. A nil input is a nil
// collection.
func PurchaseCollectionOf(rows model.Rows) PurchaseCollection {
	if rows == nil {
		return nil
	}
	out := make(PurchaseCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Purchase)
	}
	return out
}

func purchaseOf(e model.Entity) *Purchase {
	row, _ := e.(*Purchase)
	return row
}

// purchaseColumn turns a closure over PurchaseQuery into one over the core builder, so
// passing func(*PurchaseQuery) where a column goes adds a parenthesised group.
func purchaseColumn(column any) any {
	if group, ok := column.(func(*PurchaseQuery)); ok {
		return func(b *model.Builder) { group(&PurchaseQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *PurchaseQuery) Clone() *PurchaseQuery { return &PurchaseQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*PurchaseQuery) in place of the column adds a group.
func (q *PurchaseQuery) Where(column any, args ...any) *PurchaseQuery {
	q.b.Where(purchaseColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*PurchaseQuery) in place of the column adds a group.
func (q *PurchaseQuery) OrWhere(column any, args ...any) *PurchaseQuery {
	q.b.OrWhere(purchaseColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *PurchaseQuery) WhereNot(column any, args ...any) *PurchaseQuery {
	q.b.WhereNot(purchaseColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *PurchaseQuery) OrWhereNot(column any, args ...any) *PurchaseQuery {
	q.b.OrWhereNot(purchaseColumn(column), args...)
	return q
}

func (q *PurchaseQuery) WhereIn(column any, values []any) *PurchaseQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *PurchaseQuery) WhereNotIn(column any, values []any) *PurchaseQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *PurchaseQuery) WhereNull(columns ...any) *PurchaseQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *PurchaseQuery) WhereNotNull(columns ...any) *PurchaseQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *PurchaseQuery) WhereBetween(column any, from, to any) *PurchaseQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *PurchaseQuery) WhereColumn(first any, args ...any) *PurchaseQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *PurchaseQuery) WhereKey(id any) *PurchaseQuery {
	q.b.WhereKey(id)
	return q
}

func (q *PurchaseQuery) WhereExists(callback func(*query.Builder)) *PurchaseQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *PurchaseQuery) WhereNotExists(callback func(*query.Builder)) *PurchaseQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *PurchaseQuery) WhereHas(relation string, callback func(*query.Builder)) *PurchaseQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *PurchaseQuery) OrWhereHas(relation string, callback func(*query.Builder)) *PurchaseQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *PurchaseQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *PurchaseQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *PurchaseQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *PurchaseQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *PurchaseQuery) WhereRelation(relation string, column any, args ...any) *PurchaseQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *PurchaseQuery) OrWhereRelation(relation string, column any, args ...any) *PurchaseQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *PurchaseQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *PurchaseQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *PurchaseQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *PurchaseQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *PurchaseQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *PurchaseQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *PurchaseQuery) OrHas(relation, operator string, count int) *PurchaseQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *PurchaseQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *PurchaseQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *PurchaseQuery) OrDoesntHave(relation string) *PurchaseQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *PurchaseQuery) Select(columns ...any) *PurchaseQuery {
	q.b.Select(columns...)
	return q
}

func (q *PurchaseQuery) AddSelect(columns ...any) *PurchaseQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *PurchaseQuery) SelectRaw(expression string, bindings ...any) *PurchaseQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *PurchaseQuery) Join(table any, first any, args ...any) *PurchaseQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *PurchaseQuery) GroupBy(groups ...any) *PurchaseQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *PurchaseQuery) OrderBy(column any, direction ...string) *PurchaseQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *PurchaseQuery) OrderByDesc(column any) *PurchaseQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *PurchaseQuery) Latest(column ...string) *PurchaseQuery {
	q.b.Latest(column...)
	return q
}

func (q *PurchaseQuery) Oldest(column ...string) *PurchaseQuery {
	q.b.Oldest(column...)
	return q
}

func (q *PurchaseQuery) Limit(value int) *PurchaseQuery {
	q.b.Limit(value)
	return q
}

func (q *PurchaseQuery) Offset(value int) *PurchaseQuery {
	q.b.Offset(value)
	return q
}

func (q *PurchaseQuery) ForPage(page, perPage int) *PurchaseQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *PurchaseQuery) With(relations ...string) *PurchaseQuery {
	q.b.With(relations...)
	return q
}

func (q *PurchaseQuery) WithCount(relations ...string) *PurchaseQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *PurchaseQuery) WithExists(relation string) *PurchaseQuery {
	q.b.WithExists(relation)
	return q
}

func (q *PurchaseQuery) WithSum(relation, column string) *PurchaseQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *PurchaseQuery) WithAvg(relation, column string) *PurchaseQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *PurchaseQuery) WithMin(relation, column string) *PurchaseQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *PurchaseQuery) WithMax(relation, column string) *PurchaseQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *PurchaseQuery) Without(relations ...string) *PurchaseQuery {
	q.b.Without(relations...)
	return q
}

func (q *PurchaseQuery) WithoutGlobalScope(identifier string) *PurchaseQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *PurchaseQuery) WithoutGlobalScopes(identifiers ...string) *PurchaseQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *PurchaseQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (PurchaseCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return PurchaseCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *PurchaseQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Purchase, error) {
	e, err := q.b.First(ctx, g, columns...)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Purchase, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Purchase, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Purchase, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Purchase, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Purchase, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Purchase, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Purchase, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (PurchaseCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return PurchaseCollectionOf(rows), err
}

func (q *PurchaseQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Purchase, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Purchase, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Purchase, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Purchase, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return purchaseOf(e), err
}

func (q *PurchaseQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (PurchaseCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return PurchaseCollectionOf(rows), meta, err
}

func (q *PurchaseQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (PurchaseCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return PurchaseCollectionOf(rows), meta, err
}

func (q *PurchaseQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (PurchaseCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return PurchaseCollectionOf(rows), meta, err
}

func (q *PurchaseQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(PurchaseCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(PurchaseCollectionOf(rows), page)
	})
}

func (q *PurchaseQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Purchase, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(purchaseOf(e), index)
	})
}

func (q *PurchaseQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Purchase, error] {
	return func(yield func(*Purchase, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(purchaseOf(e), err) {
				return
			}
		}
	}
}

func (q *PurchaseQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *PurchaseQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *PurchaseQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *PurchaseQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *PurchaseQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *PurchaseQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *PurchaseQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *PurchaseQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *PurchaseQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *PurchaseQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *PurchaseQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *PurchaseQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *PurchaseQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *PurchaseQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *PurchaseQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *PurchaseQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *PurchaseQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *PurchaseQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *PurchaseQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c PurchaseCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c PurchaseCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c PurchaseCollection) Find(key any) *Purchase { return purchaseOf(c.Rows().Find(key)) }

func (c PurchaseCollection) FindOrFail(key any) (*Purchase, error) {
	e, err := c.Rows().FindOrFail(key)
	return purchaseOf(e), err
}

func (c PurchaseCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c PurchaseCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c PurchaseCollection) Only(keys ...any) PurchaseCollection {
	return PurchaseCollectionOf(c.Rows().Only(keys...))
}

func (c PurchaseCollection) Except(keys ...any) PurchaseCollection {
	return PurchaseCollectionOf(c.Rows().Except(keys...))
}

func (c PurchaseCollection) Unique() PurchaseCollection {
	return PurchaseCollectionOf(c.Rows().Unique())
}

func (c PurchaseCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c PurchaseCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c PurchaseCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c PurchaseCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (PurchaseCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return PurchaseCollectionOf(rows), err
}

func (c PurchaseCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Purchase; it shadows the untyped one the
// embedded model promotes.
func (row *Purchase) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Purchase, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return purchaseOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Purchase) Replicate(except ...string) (*Purchase, error) {
	e, err := row.Model.Replicate(except...)
	return purchaseOf(e), err
}
