package wallet

import (
	"errors"
	"time"

	"github.com/arandu-io/framework/data"
	"github.com/arandu-io/hesape/database/model"
)

// purchasesTable is the projection of what was bought from whom.
const purchasesTable = "wallet_purchases"

// PurchaseKind is what a purchase row records.
type PurchaseKind string

// The kinds a purchase row can be. What was paid for is told apart from what
// was given, because "has this person already got one" is asked both ways and
// the answer differs: an application that sells a licence wants the one they
// paid for, and one that hands out a bonus wants either.
const (
	// PurchasePaid is a line somebody bought for themselves.
	PurchasePaid PurchaseKind = "paid"
	// PurchaseGift is a line somebody bought for somebody else. The money left
	// the payer and the line belongs to the beneficiary.
	PurchaseGift PurchaseKind = "gift"
	// PurchaseRefund is a line that was undone. It names the line it settles,
	// and appending it is what takes a purchase back -- the row that recorded
	// the purchase is never touched.
	PurchaseRefund PurchaseKind = "refund"
)

// The refusals about a purchase. Each is a different thing to fix: a line that
// was already undone is the second attempt, and a line that cannot be undone is
// the one being named.
var (
	// ErrAlreadyRefunded is returned when a line has already been given back.
	// The refusal comes from a unique index, so two concurrent refunds of one
	// line cannot both succeed.
	ErrAlreadyRefunded = errors.New("wallet: this line has already been refunded")

	// ErrNotRefundable is returned when the line named is itself a refund.
	// Undoing a refund is buying the thing again, with its own record, rather
	// than a second refund of the same line.
	ErrNotRefundable = errors.New("wallet: a refund cannot itself be refunded")

	// ErrPurchaseOperation is returned when a reversal names an operation that
	// bought or refunded something. A basket is undone by its lines, so that a
	// basket half of which was already given back cannot be given back whole.
	ErrPurchaseOperation = errors.New("wallet: a purchase is undone line by line, with a refund")
)

// Purchase is one line of a basket, recorded as it was paid.
//
// It is the projection of "who bought what from whom", and it is what "has this
// already been bought" reads: the ledger says money moved between two wallets
// and would have to be read with the catalogue beside it to say what for, which
// is a question every application asks and none of them should have to assemble.
//
// It is also the receipt of that line. Every number the arithmetic used is on
// it -- the price, the quantity, what was taken off, what the fee was computed
// from, the exact fraction, both bounds, what left the payer and what reached
// the receiver -- so the line can be recomputed from the row alone, by somebody
// who has neither the catalogue that priced it nor the code that called it.
// That is the same standard the recorded rates and charges are held to, and it
// is what lets a refund move back exactly what moved without reading anything
// else.
//
// Rows are appended and never changed. A line that was given back is a second
// row naming the first, so what was bought stays readable after it is undone --
// which a status column that is rewritten in place cannot do.
type Purchase struct {
	model.Model[Purchase]

	// ID is the identifier, generated by the application.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to, written from the Grant.
	TenantID string `db:"tenant_id"`

	// OperationID is the operation that paid for this line, and Position is
	// where the line sat in the basket, counting from zero.
	OperationID string `db:"operation_id"`
	Position    int    `db:"position"`

	// PayerWalletID is the wallet the money left.
	PayerWalletID string `db:"payer_wallet_id"`

	// OwnerWalletID is whose purchase this is. It is the payer on an ordinary
	// line and the beneficiary on a gift, which is the whole of what a gift
	// changes: the money is still the payer's and the thing bought is not.
	OwnerWalletID string `db:"owner_wallet_id"`

	// ReceiverWalletID is the wallet the money arrived in.
	ReceiverWalletID string `db:"receiver_wallet_id"`

	// ProductKey is what was bought, as the application names it.
	ProductKey string `db:"product_key"`

	// Quantity is how many of it.
	Quantity int `db:"quantity"`

	// Currency is the money every amount below is counted in, and DecimalPlaces
	// its scale. Both are copied onto the row rather than read back off a
	// wallet, because a wallet is a live record and a purchase is a fact about a
	// moment.
	Currency      Currency `db:"currency"`
	DecimalPlaces int      `db:"decimal_places"`

	// PricePerItem is what one of the product cost, and RequestedAmount the
	// price multiplied by the quantity, before anything was taken off.
	PricePerItem    Amount `db:"price_per_item"`
	RequestedAmount Amount `db:"requested_amount"`

	// Discount is what the payer was charged less on this line, and BaseAmount
	// what the fee was computed from: the requested amount less the discount.
	Discount   Amount `db:"discount"`
	BaseAmount Amount `db:"base_amount"`

	// FeeNumerator and FeeDenominator are the exact fraction the fee was, and
	// FeeMinimum and FeeMaximum the bounds it was held between. All four are
	// recorded even where a bound decided the fee, because which of them decided
	// is the first question anybody asks about a fee that is not the share of
	// the payment.
	FeeNumerator   int64  `db:"fee_numerator"`
	FeeDenominator int64  `db:"fee_denominator"`
	FeeMinimum     Amount `db:"fee_minimum"`
	FeeMaximum     Amount `db:"fee_maximum"`

	// FeeDeductible says who paid it: false is the payer, on top of the line,
	// and true is the receiver, out of what arrived.
	FeeDeductible Flag `db:"fee_deductible"`

	// FeeAmount is what was actually charged, and FeeWalletID the wallet it was
	// credited to.
	FeeAmount   Amount `db:"fee_amount"`
	FeeWalletID string `db:"fee_wallet_id"`

	// Rounding is the rule that produced FeeAmount from the exact share, and
	// RemainderNumerator what truncating it left, over RemainderDenominator.
	Rounding             Rounding `db:"rounding"`
	RemainderNumerator   int64    `db:"remainder_numerator"`
	RemainderDenominator int64    `db:"remainder_denominator"`

	// PaidAmount is what left the payer for this line, and CreditedAmount what
	// reached the receiver. They differ by the fee when the payer paid it, and
	// are equal when the receiver did.
	//
	// Both are written rather than derived, because they are what a refund moves
	// back: a line given back reads its own row and returns exactly what left
	// and exactly what arrived, without recomputing a fee that a schedule might
	// answer differently today.
	PaidAmount     Amount `db:"paid_amount"`
	CreditedAmount Amount `db:"credited_amount"`

	// Kind is what this row records.
	Kind PurchaseKind `db:"kind"`

	// SettlesID is the line this row settles: the purchase a refund undoes, and
	// its own identifier where it settles nothing.
	//
	// With the kind beside it in a unique index, that one column carries the
	// whole rule that a line is refunded at most once -- and a row that settles
	// nothing collides with nothing, not even with the refund naming it, because
	// the two differ in kind.
	SettlesID string `db:"settles_id"`

	// Sequence is the position, in the owner's ledger, of the movement this row
	// came from.
	//
	// It is what a purchase is ordered by, and it is a number this package
	// writes rather than a timestamp: two purchases inside one tick of the clock
	// are two rows an ORDER BY over time cannot tell apart, and "the most recent
	// one" is exactly the question asked here.
	Sequence int64 `db:"sequence"`

	// CreatedAt is when the line was written, in UTC.
	CreatedAt time.Time `db:"created_at"`
}

// Purchases returns the configured model for the purchases table.
func Purchases(db *data.DB) *model.Model[Purchase] {
	m := model.NewModel[Purchase](purchasesTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// Refunds is the line this row gave back, and the empty string where it gave
// back nothing.
func (p Purchase) Refunds() string {
	if p.Kind != PurchaseRefund || p.SettlesID == p.ID {
		return ""
	}
	return p.SettlesID
}

// Gift reports that the money was one wallet's and the thing bought another's.
func (p Purchase) Gift() bool { return p.Kind == PurchaseGift }

// Free reports that this line moved no money.
//
// It is what the row says rather than a kind of its own: a free line is bought
// or given exactly as a paid one is, and what makes it free is the price on it.
// A second kind would mean two answers to "has this person got one", which is
// the question the record exists for.
func (p Purchase) Free() bool { return p.PaidAmount == 0 && p.CreditedAmount == 0 }

// Price is what one of the product cost, read at the scale it was counted at.
func (p Purchase) Price() Money {
	return Money{Amount: p.PricePerItem, Currency: p.Currency, DecimalPlaces: p.DecimalPlaces}
}

// Requested is the price times the quantity, before anything was taken off.
func (p Purchase) Requested() Money {
	return Money{Amount: p.RequestedAmount, Currency: p.Currency, DecimalPlaces: p.DecimalPlaces}
}

// Paid is what left the payer for this line.
func (p Purchase) Paid() Money {
	return Money{Amount: p.PaidAmount, Currency: p.Currency, DecimalPlaces: p.DecimalPlaces}
}

// Credited is what reached the receiver.
func (p Purchase) Credited() Money {
	return Money{Amount: p.CreditedAmount, Currency: p.Currency, DecimalPlaces: p.DecimalPlaces}
}

// Fee is what was charged on this line, read at the scale it was counted at.
func (p Purchase) Fee() Money {
	return Money{Amount: p.FeeAmount, Currency: p.Currency, DecimalPlaces: p.DecimalPlaces}
}

// Schedule is the fee this line was charged under, as it was quoted.
func (p Purchase) Schedule() FeeSchedule {
	return FeeSchedule{
		Numerator:   p.FeeNumerator,
		Denominator: p.FeeDenominator,
		Minimum:     p.FeeMinimum,
		Maximum:     p.FeeMaximum,
		Deductible:  bool(p.FeeDeductible),
		WalletID:    p.FeeWalletID,
	}
}

// PurchaseQuery is one question about what a wallet already has.
//
// It names the three things that make a purchase what it is -- whose it would
// be, who was paid for it, and what it was -- because any two of them are a
// question with several answers, and a caller that had to filter the third in
// its own code would be a caller reading rows it was told not to have.
type PurchaseQuery struct {
	// OwnerWalletID is whose purchase it would be. On a gift that is the
	// beneficiary and not whoever paid.
	OwnerWalletID string
	// ReceiverWalletID is the wallet the money went to.
	ReceiverWalletID string
	// ProductKey is what was bought, as the application names it.
	ProductKey string
	// IncludeGifts asks about what was given as well as what was paid for.
	// False is the ordinary question: has this person bought one.
	IncludeGifts bool
}

// PurchaseResource is the list of fields one purchase may answer with.
//
// A declared list rather than the entity, for the reason Resource is one: an
// encoder handed the entity answers with whatever fields it happens to have,
// including the ones somebody adds later without opening the handler.
type PurchaseResource struct {
	id            string
	operationID   string
	position      int
	payerWalletID string
	ownerWalletID string
	receiverID    string
	productKey    string
	quantity      int
	currency      Currency
	decimalPlaces int
	price         Amount
	requested     Amount
	discount      Amount
	base          Amount
	fee           Amount
	feeWalletID   string
	paid          Amount
	credited      Amount
	kind          PurchaseKind
	refunds       string
	sequence      int64
	createdAt     time.Time
}

// NewPurchaseResource snapshots one purchase for the response.
func NewPurchaseResource(record Purchase) PurchaseResource {
	return PurchaseResource{
		id:            record.ID,
		operationID:   record.OperationID,
		position:      record.Position,
		payerWalletID: record.PayerWalletID,
		ownerWalletID: record.OwnerWalletID,
		receiverID:    record.ReceiverWalletID,
		productKey:    record.ProductKey,
		quantity:      record.Quantity,
		currency:      record.Currency,
		decimalPlaces: record.DecimalPlaces,
		price:         record.PricePerItem,
		requested:     record.RequestedAmount,
		discount:      record.Discount,
		base:          record.BaseAmount,
		fee:           record.FeeAmount,
		feeWalletID:   record.FeeWalletID,
		paid:          record.PaidAmount,
		credited:      record.CreditedAmount,
		kind:          record.Kind,
		refunds:       record.Refunds(),
		sequence:      record.Sequence,
		createdAt:     record.CreatedAt,
	}
}

// ToArray returns the fields that may leave, by name.
//
// Each amount leaves twice, as the integer the ledger is kept in and as the
// decimal a person reads, which is the same arrangement a balance has and for
// the same reason.
func (r PurchaseResource) ToArray() map[string]any {
	return map[string]any{
		"id":                     r.id,
		"operation_id":           r.operationID,
		"position":               r.position,
		"payer_wallet_id":        r.payerWalletID,
		"owner_wallet_id":        r.ownerWalletID,
		"receiver_wallet_id":     r.receiverID,
		"product_key":            r.productKey,
		"quantity":               r.quantity,
		"currency":               string(r.currency),
		"decimal_places":         r.decimalPlaces,
		"price_per_item_minor":   int64(r.price),
		"price_per_item":         r.price.Format(r.decimalPlaces),
		"requested_amount_minor": int64(r.requested),
		"requested_amount":       r.requested.Format(r.decimalPlaces),
		"discount_minor":         int64(r.discount),
		"discount":               r.discount.Format(r.decimalPlaces),
		"base_amount_minor":      int64(r.base),
		"base_amount":            r.base.Format(r.decimalPlaces),
		"fee_minor":              int64(r.fee),
		"fee":                    r.fee.Format(r.decimalPlaces),
		"fee_wallet_id":          r.feeWalletID,
		"paid_amount_minor":      int64(r.paid),
		"paid_amount":            r.paid.Format(r.decimalPlaces),
		"credited_amount_minor":  int64(r.credited),
		"credited_amount":        r.credited.Format(r.decimalPlaces),
		"kind":                   string(r.kind),
		"refunds":                r.refunds,
		"sequence":               r.sequence,
		"created_at":             r.createdAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields, and nothing does.
func (r PurchaseResource) With() map[string]any { return nil }

// PurchaseCollection is a page of purchases as one response.
type PurchaseCollection struct {
	records []PurchaseResource
	cursor  string
}

// NewPurchaseCollection wraps a page of purchases for the response. The cursor
// is what the next request passes back, and is empty when there is no next
// page.
func NewPurchaseCollection(records []*Purchase, cursor string) PurchaseCollection {
	resources := make([]PurchaseResource, 0, len(records))
	for _, record := range records {
		if record != nil {
			resources = append(resources, NewPurchaseResource(*record))
		}
	}
	return PurchaseCollection{records: resources, cursor: cursor}
}

// ToArray returns the page under a single key, so that the shape of the
// response does not change when a second key is added beside it.
func (c PurchaseCollection) ToArray() map[string]any {
	items := make([]map[string]any, 0, len(c.records))
	for _, record := range c.records {
		items = append(items, record.ToArray())
	}
	return map[string]any{"items": items}
}

// With returns the cursor of the next page, and nothing when there is none.
func (c PurchaseCollection) With() map[string]any {
	if c.cursor == "" {
		return nil
	}
	return map[string]any{"next_cursor": c.cursor}
}
