// Code generated by aru model:build from model.go. DO NOT EDIT.

package wallet

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Wallets starts a query on the table of Wallet, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Wallets(db model.DB) *WalletQuery { return &WalletQuery{b: walletTable.Query(db)} }

// WalletQuery is a query on the table of Wallet.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Wallet rows or a value; there is
// no way to run one without a Grant.
type WalletQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *WalletQuery) Base() *model.Builder { return q.b }

// New returns an empty Wallet on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *WalletQuery) New() (*Wallet, error) {
	e, err := q.b.NewModelInstance(nil)
	return walletOf(e), err
}

// WalletCollection is rows of Wallet, as a query returns them.
type WalletCollection []*Wallet

// WalletCollectionOf converts rows of the table of Wallet. A nil input is a nil
// collection.
func WalletCollectionOf(rows model.Rows) WalletCollection {
	if rows == nil {
		return nil
	}
	out := make(WalletCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Wallet)
	}
	return out
}

func walletOf(e model.Entity) *Wallet {
	row, _ := e.(*Wallet)
	return row
}

// walletColumn turns a closure over WalletQuery into one over the core builder, so
// passing func(*WalletQuery) where a column goes adds a parenthesised group.
func walletColumn(column any) any {
	if group, ok := column.(func(*WalletQuery)); ok {
		return func(b *model.Builder) { group(&WalletQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *WalletQuery) Clone() *WalletQuery { return &WalletQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*WalletQuery) in place of the column adds a group.
func (q *WalletQuery) Where(column any, args ...any) *WalletQuery {
	q.b.Where(walletColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*WalletQuery) in place of the column adds a group.
func (q *WalletQuery) OrWhere(column any, args ...any) *WalletQuery {
	q.b.OrWhere(walletColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *WalletQuery) WhereNot(column any, args ...any) *WalletQuery {
	q.b.WhereNot(walletColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *WalletQuery) OrWhereNot(column any, args ...any) *WalletQuery {
	q.b.OrWhereNot(walletColumn(column), args...)
	return q
}

func (q *WalletQuery) WhereIn(column any, values []any) *WalletQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *WalletQuery) WhereNotIn(column any, values []any) *WalletQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *WalletQuery) WhereNull(columns ...any) *WalletQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *WalletQuery) WhereNotNull(columns ...any) *WalletQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *WalletQuery) WhereBetween(column any, from, to any) *WalletQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *WalletQuery) WhereColumn(first any, args ...any) *WalletQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *WalletQuery) WhereKey(id any) *WalletQuery {
	q.b.WhereKey(id)
	return q
}

func (q *WalletQuery) WhereExists(callback func(*query.Builder)) *WalletQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *WalletQuery) WhereNotExists(callback func(*query.Builder)) *WalletQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *WalletQuery) WhereHas(relation string, callback func(*query.Builder)) *WalletQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *WalletQuery) OrWhereHas(relation string, callback func(*query.Builder)) *WalletQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *WalletQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *WalletQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *WalletQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *WalletQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *WalletQuery) WhereRelation(relation string, column any, args ...any) *WalletQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *WalletQuery) OrWhereRelation(relation string, column any, args ...any) *WalletQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *WalletQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *WalletQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *WalletQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *WalletQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *WalletQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *WalletQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *WalletQuery) OrHas(relation, operator string, count int) *WalletQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *WalletQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *WalletQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *WalletQuery) OrDoesntHave(relation string) *WalletQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *WalletQuery) Select(columns ...any) *WalletQuery {
	q.b.Select(columns...)
	return q
}

func (q *WalletQuery) AddSelect(columns ...any) *WalletQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *WalletQuery) SelectRaw(expression string, bindings ...any) *WalletQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *WalletQuery) Join(table any, first any, args ...any) *WalletQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *WalletQuery) GroupBy(groups ...any) *WalletQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *WalletQuery) OrderBy(column any, direction ...string) *WalletQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *WalletQuery) OrderByDesc(column any) *WalletQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *WalletQuery) Latest(column ...string) *WalletQuery {
	q.b.Latest(column...)
	return q
}

func (q *WalletQuery) Oldest(column ...string) *WalletQuery {
	q.b.Oldest(column...)
	return q
}

func (q *WalletQuery) Limit(value int) *WalletQuery {
	q.b.Limit(value)
	return q
}

func (q *WalletQuery) Offset(value int) *WalletQuery {
	q.b.Offset(value)
	return q
}

func (q *WalletQuery) ForPage(page, perPage int) *WalletQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *WalletQuery) With(relations ...string) *WalletQuery {
	q.b.With(relations...)
	return q
}

func (q *WalletQuery) WithCount(relations ...string) *WalletQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *WalletQuery) WithExists(relation string) *WalletQuery {
	q.b.WithExists(relation)
	return q
}

func (q *WalletQuery) WithSum(relation, column string) *WalletQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *WalletQuery) WithAvg(relation, column string) *WalletQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *WalletQuery) WithMin(relation, column string) *WalletQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *WalletQuery) WithMax(relation, column string) *WalletQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *WalletQuery) Without(relations ...string) *WalletQuery {
	q.b.Without(relations...)
	return q
}

func (q *WalletQuery) WithoutGlobalScope(identifier string) *WalletQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *WalletQuery) WithoutGlobalScopes(identifiers ...string) *WalletQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *WalletQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (WalletCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return WalletCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *WalletQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Wallet, error) {
	e, err := q.b.First(ctx, g, columns...)
	return walletOf(e), err
}

func (q *WalletQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Wallet, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return walletOf(e), err
}

func (q *WalletQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Wallet, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return walletOf(e), err
}

func (q *WalletQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Wallet, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return walletOf(e), err
}

func (q *WalletQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Wallet, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return walletOf(e), err
}

func (q *WalletQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Wallet, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return walletOf(e), err
}

func (q *WalletQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Wallet, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return walletOf(e), err
}

func (q *WalletQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Wallet, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return walletOf(e), err
}

func (q *WalletQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (WalletCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return WalletCollectionOf(rows), err
}

func (q *WalletQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Wallet, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return walletOf(e), err
}

func (q *WalletQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Wallet, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return walletOf(e), err
}

func (q *WalletQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Wallet, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return walletOf(e), err
}

func (q *WalletQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Wallet, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return walletOf(e), err
}

func (q *WalletQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (WalletCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return WalletCollectionOf(rows), meta, err
}

func (q *WalletQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (WalletCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return WalletCollectionOf(rows), meta, err
}

func (q *WalletQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (WalletCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return WalletCollectionOf(rows), meta, err
}

func (q *WalletQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(WalletCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(WalletCollectionOf(rows), page)
	})
}

func (q *WalletQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Wallet, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(walletOf(e), index)
	})
}

func (q *WalletQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Wallet, error] {
	return func(yield func(*Wallet, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(walletOf(e), err) {
				return
			}
		}
	}
}

func (q *WalletQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *WalletQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *WalletQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *WalletQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *WalletQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *WalletQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *WalletQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *WalletQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *WalletQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *WalletQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *WalletQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *WalletQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *WalletQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *WalletQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *WalletQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *WalletQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *WalletQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *WalletQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *WalletQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c WalletCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c WalletCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c WalletCollection) Find(key any) *Wallet { return walletOf(c.Rows().Find(key)) }

func (c WalletCollection) FindOrFail(key any) (*Wallet, error) {
	e, err := c.Rows().FindOrFail(key)
	return walletOf(e), err
}

func (c WalletCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c WalletCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c WalletCollection) Only(keys ...any) WalletCollection {
	return WalletCollectionOf(c.Rows().Only(keys...))
}

func (c WalletCollection) Except(keys ...any) WalletCollection {
	return WalletCollectionOf(c.Rows().Except(keys...))
}

func (c WalletCollection) Unique() WalletCollection { return WalletCollectionOf(c.Rows().Unique()) }

func (c WalletCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c WalletCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c WalletCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c WalletCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (WalletCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return WalletCollectionOf(rows), err
}

func (c WalletCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Wallet; it shadows the untyped one the
// embedded model promotes.
func (row *Wallet) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Wallet, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return walletOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Wallet) Replicate(except ...string) (*Wallet, error) {
	e, err := row.Model.Replicate(except...)
	return walletOf(e), err
}
